### ISSUE TITLE
libretro-fetch.sh not downloading all the cores

### ISSUE THREAD

**Issue by amunozf** [libretro/libretro-super#1054]
When I try to get all the cores with the command "./libretro-fetch.sh" or "make", it stops at Flycast:

```
=== Flycast
libretro_fetch:No URL set to fetch Flycast via git.
Makefile:7: recipe for target 'fetch' failed
make: *** [fetch] Error 1
```
Only these cores are properly downloaded: mednafen_snes, snes9x, bsnes_accuracy, snes9x2002, bsnes_balanced, snes9x2005, bsnes_cplusplus98, snes9x2010, bsnes_mercury_accuracy, bsnes_mercury_balanced, bsnes_mercury_performance and bsnes_performance. 

Everything seems to work fine until Flycast, then no more cores are downloaded.

I could download them all with no problems a few weeks ago. This must be a recent change; perhaps it's got something to do with "Renamed to flycast", but I don't really know.

**Comment by hizzlekizzle** [comment]
Are you fetching for x86 (32-bit)?

**Comment by amunozf** [comment]
I'm fetching for Linux aarch64

**Comment by hizzlekizzle** [comment]
Can you try my fork? I spotted a typo, but it was in the linux x86 recipe, which is why I asked which arch/platform you're building for.

https://github.com/hizzlekizzle/libretro-super

**Comment by amunozf** [comment]
I followed these steps with your fork:

```
rm -rf libretro-super
git clone https://github.com/hizzlekizzle/libretro-super/
cd libretro-super
./libretro-fetch.sh
```
And I got the same error:

```
=== Flycast
libretro_fetch:No URL set to fetch Flycast via git.
```

**Comment by amunozf** [comment]
I've just tried the same with my AMD64 laptop and I get the same error.

**Comment by amunozf** [comment]
With your changes in both files, flycast is properly downloaded and it goes on to download the next cores.

Thank you.

**Comment by hizzlekizzle** [comment]
No problem. I have a PR open to make those changes to the main repo, so once it's merged, this issue will close automatically.
Thanks for reporting and testing!
