### ISSUE TITLE
[Content Downloader] TIC-80 Shadow Over The Twelve Lands

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-super#1068]
In looking for TIC-80 content for the Content Downloader, I've contacted the developer behind [Shadow Over The Twelve Lands](https://tic.computer/play?cart=873), and they are open to having it hosted on the Content Downloader.

The file:
https://tic.computer/cart/7d8068f737577be1ec02b7e889ad475a/cart.tic

```
Shadow Over The Twelves Lands.tic
```

Source is here: https://github.com/btco/so12l

**Comment by hizzlekizzle** [comment]
that game is pretty great! I'll get it up there

**Comment by RobLoach** [comment]
Worked here! Thanks a lot.
