### ISSUE TITLE
[Request] to include libneocd_libretro.dll on the buildbot

### ISSUE THREAD

**Issue by klepp0906** [libretro/libretro-super#1111]
Figured id get this in. Bparker said make a stink for inclusion here - so thats what im doing.

As per my other issue report on the RA issues tracker, the subsystem stuff ala playlist is incomplete and broken. Having this core in circumvents that issue entirely. Plus more options are a win.

https://github.com/libretro/neocd_libretro

for now i built it myself which caused issues with dependencies which left me having to build retroarch myself which leaves me without the ability to serial-update via stellar like I usually do.. SO youd be doing me a great personal service allowing me to return to regular updating with stellar and doing everyone else a service by having a core available that has no issues caused by subsystem AND includes chd support.

/lobby

**Comment by fabrice-martinez** [comment]
Lemme know if you need help with this ;)

**Comment by klepp0906** [comment]
help with lobbying to get it included with the RA buildbot? sure! :P  (J/K i know your the author)

For now, i ended up reverting back to the fbneo core and dealing with the subsystem issues.

the problem with this core (its otherwise amazing!) is that like i mentioned, it requires building RA myself every time (which by itself i could maybe live with) due to the libraries.   Where it gets crazy as ive found, is that it would also require me building all cores that depend on the same library (libwinpthread-1.dll i think was the offender maybe) as well.  (and there are many).  

Now this is well above my head, and understanding - but unless it can be included in the buildbot to be on the same page with retroarch as far as libraries go, or the stuff on the git can be made to match what RA uses (i think that was/is dependent on what was on your system when you wrote it?)  then im going to have to pick my battle on this one.

Fortunately having this included with the rest of the RA cores on the buildbot is good for everyone.  Just not the guy who has to set it up i guess >.<

**Comment by fabrice-martinez** [comment]
The problem is that RetroArch is build with an obsolete version of MSYS2. When you build the core with an up to date MSYS2 you'll find that libstdc++-6 (or something like that) is incompatible. 

What I have found (Warning: May cause crashes) is that libstdc++ is generally retro compatible, meaning I replaced the one in RetroArch's distribution with the one from my MSYS2 and everything works. I would not recommend this for general usage though.

Another solution would be to use the exact distribution of MSYS2 RetroArch is using, I don't know if it's publicly available.

Last solution is to have the core built by buildbot and the problem disappears entirely ;)

**Comment by klepp0906** [comment]
ah.  good information. thank you for filling me in.  Seems like the buildbot route is going to be the way to go.   That always was the best option anyhow.

i built another core (freechaf) and have had 0 problems whatsoever so i imagine its wholly dependent on the libraries the core uses etc. 

at least i know its something to watch out for in the future. 

Thank you for the core, and heres to hoping someone will take notice and get it in there.   After all nobody should have to depend on a subsystem if a standalone core exists, especially considering the current unfinished state of subsystem stuff. 

Plus - all that aside, options are great.  Its why we have several different genesis cores, psx cores, etc etc.

**Comment by barbudreadmon** [comment]
@fabrice-martinez The buildbot expect every external libs to be provided and linked statically, maybe include them in the repo or download them through cmake.
See https://github.com/libretro/libretro-super/commit/df268721b3a4d1b5c8965e8a2ac0f3b49fdcbc42 and the build log at http://paste.libretro.com/160776

**Comment by fabrice-martinez** [comment]
Yes I was thinking of including [libretro-deps](https://github.com/libretro/libretro-deps) but no makefiles are provided.
Another idea would be to include the necessary libs in the repo.
I'll need to figure a way to have cmake build the libs as prerequisite and static link them, or use the distro provided version with dynamic link if available.

**Comment by klepp0906** [comment]
been watching this like a hawk.   Sincerely appreciate you still working on it :)  I just re-compiled the core last night actually as I needed the name of the dll (and i recalled it being a bit un-conventional compared to other cores) to add to my shortcut parser in preparation for that fateful day it makes it onto the buildbot lol.

**Comment by MRDeu** [comment]
@fabrice-martinez Is possible to update the core of NeoCD with the latest changes on his website?

Thanks for that great core and for the CHD support.

**Comment by Ghabry** [comment]
At first my usual rant that I find it ridiculous that libretro cores are expected to "bake in" all dependencies. All the (cross compiled) dependencies should be compiled and installed provided through some general  buildscript which the cores can simply include. Would make creating cores with external dependencies sooooo much easier.

How I got it working (gigantic time waste but the only solution...):
To get this working for the core I maintain (easyrpg-player) I used our already available buildscript repository from https://github.com/EasyRPG/buildscripts , downloaded all the deps, extracted them, applied patches, copy-pasted all that crap in the libretro-core repo, the result is "voodoo build", available here: https://github.com/libretro/easyrpg-libretro/tree/master/builds/libretro/deps/libretro and a modified Makefile.libretro which invokes "voodoo build" and cmake: https://github.com/libretro/easyrpg-libretro/blob/master/builds/libretro/Makefile.libretro

A gigantic hack, but works >.>

**Comment by barbudreadmon** [comment]
@Ghabry you should be able to handle the downloading/patching if you use cmake though (buildbot is compatible with cmake, even if very few cores are using it).

**Comment by klepp0906** [comment]
this pizza still in the oven?  neocd is on my xmas wish list and we're getting closer by the day.   If that  doesnt compel you, i dont know what will :P

**Comment by gouchi** [comment]
But it has already been added to [buildbot using CMake](https://github.com/libretro/libretro-super/pull/1132/files) but is [currently failing to build](http://paste.libretro.com/160882).
