### ISSUE TITLE
[PicoDrive] Segmentation fault on Raspberry Pi 3B

### ISSUE THREAD

**Issue by metchebe** [libretro/libretro-super#1116]
Hardware: Raspberry Pi 3B
OS: Raspbian Buster
RetroArch: v1.7.7 -- da1ff54 -- Compiler: GCC (8.3.0) 32-bit Built: Aug 14 2019

The ARM PicoDrive builds from the buildbot fail with a segmentation fault on my Raspberry Pi 3B. This happens with both `armhf` and `armv7-neon-hf` builds.

On the other hand, the PicoDrive core .so from Lakka RPi2 v2.2.2 works without issue.

Related issue: https://github.com/libretro/ludo/issues/185

**Comment by gouchi** [comment]
For information, [how we compile it](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/picodrive/package.mk) on Lakka.

**Comment by metchebe** [comment]
Actually, PicoDrive compiles a binary that works OK with the current libretro-super script on my Rasbperry Pi 3B:

    ./libretro-build.sh picodrive

The current armv7 binary on the buildbot is very old (2019-Jan-10), perhaps it would be enough just to rebuild it.

**Comment by kivutar** [comment]
This is the build error on the buildbot: http://paste.libretro.com/171523

```
./cyclone_gen
./cyclone_gen: 1: ./cyclone_gen: Syntax error: word unexpected (expecting ")")
Makefile:15: recipe for target 'Cyclone.s' failed
```

**Comment by kivutar** [comment]
picodrive succeeded to build for recipes/linux/cores-linux-armhf-generic but failed for recipes/linux/cores-linux-arm7neonhf
is arm-linux-gnueabihf-gcc symlinked to gcc in this recipe?

**Comment by kivutar** [comment]
Fixed, had to clean cyclone
