### ISSUE TITLE
o2em core fails to build under fedora linux

### ISSUE THREAD

**Issue by aeder** [libretro/libretro-super#114]
When compiling, the script fails with the following error message:

relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
libretro.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
gmake: *** [o2em_libretro.dll] Error 1
Failed to build o2em
cp: cannot stat «o2em_libretro.so»: No such file or directory

This happens on Fedora 20 KDE Spin. GCC version: 4.8.3

**Comment by twinaphex** [comment]
This should no longer be an issue.

If it still happens, re-open this issue.
