### ISSUE TITLE
[macOS] fails to build neocd

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-super#1189]
Libretro super fails to build neocd for OSX with the error:
```
src/chdfile.cpp:46:42: error: no member named 'malloc' in namespace 'std'; did you mean simply 'malloc'?
    m_hunkData = reinterpret_cast<char*>(std::malloc(chdHeader->hunkbytes));
```
If I make neocd on my local machine though it builds just fine and doesn't fail at this point.

**Comment by gouchi** [comment]
Should be fixed with [this commit](https://github.com/libretro/neocd_libretro/commit/2a20d2cda07f59acb145921ac3ead336cb42be97).

**Comment by gouchi** [comment]
It is now available for [macOS x86_64](http://buildbot.libretro.com/nightly/apple/osx/x86_64/latest/).

**Comment by zach-morris** [comment]
Works now, thank you!
