### ISSUE TITLE
Mednafen Saturn Core in LaunchBox 

### ISSUE THREAD

**Issue by dovellonsky** [libretro/libretro-super#1217]
I found a bug that is driving me crazy. This BUG occurs only in Big Box and not the desktop Launchbox.
Basically the Bug comes out with Mendafen Saturn's CORE in retroarch 1.8.4 . If I start a game from the desktop launchbox, it works perfectly, if I start the same game from the Big Box the Mednafen core starts to have problems and has impressive drops in framerates.
I also tried to eliminate the "LOADING PAGE" because I thought it could interfere with the loading of the core, unfortunately I don't get any improvement. I can't understand what breaks the mednafen saturn core from BigBox and not from desktop launchbox .

Any Help ?

PC AMd Ryzen 3 , 8 gb Ram , SSD , Gpu AMD 560 4gb .

**Comment by hizzlekizzle** [comment]
We don't support Launchbox/Big Box. You'd have to take it up with him/them.

**Comment by dovellonsky** [comment]
Can you at least confirm that the performance in Open GL is very low, while in Direct 3d 12 the speed is optimal?

**Comment by hizzlekizzle** [comment]
The saturn core is software rendered, so any performance disparity would be the work of the GPU+driver rather than the core itself.

**Comment by dovellonsky** [comment]
> The saturn core is software rendered, so any performance disparity would be the work of the GPU+driver rather than the core itself.

Thank You !
