### ISSUE TITLE
[help requested] Please help adding Elektronika BK-0010 emulator

### ISSUE THREAD

**Issue by phcoder** [libretro/libretro-super#1225]
Hello. Elektronika BK-0010 is a Soviet home computer I had in my childhood. I ported BK emulator to libretro: https://github.com/arcade-mini/bk-emulator . arcade-mini asks for libretro variant to be maintained under libretro/ . Also it needs to be included in libretro-super. Can somebody help me with it?

**Comment by hizzlekizzle** [comment]
This is great! I think it should be pretty straightforward to get going.

Do you know what platforms we should target with it? Just Windows/Mac/Linux? Android/iOS? Is it usable without a keyboard?

**Comment by phcoder** [comment]
I tested mainly on Android but also on Linux. Without keyboard: it depends on the game. Few are playable with just joystick/gamepad

**Comment by gouchi** [comment]
I compiled and succeeded to launch it on Linux.

Needs at least two bios [MONIT10.ROM and FOCAL10.ROM](https://github.com/emestee/bk-emulator/tree/master/Rom).

**Comment by gouchi** [comment]
This issue can be closed now as you @phcoder [added it to buildbot](https://github.com/libretro/libretro-super/pull/1249) ;-)
