### ISSUE TITLE
[Issue] Problem with ppsspp core in Windows

### ISSUE THREAD

**Issue by Immersion95** [libretro/libretro-super#1302]
Hi,

ppsspp's core in Windows is old (from Oct, 9th). It's strange as https://github.com/libretro/ppsspp is being worked on constantly.

I would have opened the issues there but it is not allowed as the moment, maybe it is being published in the near future ?

The issue I openened there https://github.com/twinaphex/ppsspp/issues/25 has been moved on another branch https://github.com/twinaphex/ppsspp

**Comment by hizzlekizzle** [comment]
The build failure is:

**Comment by Immersion95** [comment]
Was this problem known since October ?

Also, is there a reason why we can't post issue on the officiel libretro ppssspp github ?

**Comment by hizzlekizzle** [comment]
I guess so. People have mentioned there being a problem, and I know I've looked into it at least once, but I forgot about it and there was never an issue created for it, so it just slipped through the cracks, it seems.

Issues are disabled at the actual repo. Dunno why that is, but I don't want to reenable them without finding out why first.

**Comment by Immersion95** [comment]
Regarding "<mfreadwrite.h>", I'm sorry that I can't be of any help :(.

Is that a difficult thing to fix ?

**Comment by hizzlekizzle** [comment]
It looks like that might have just been a symptom of bigger problems. m4xw pushed some PRs to hrydgard's repo, so hopefully this will be resolved soon.

**Comment by Immersion95** [comment]
Thanks a lot !

- Standalone doesn't have exclusive fullscreen so there are 2-3 frames of input lag.

- The current ppsspp core has [3 frames of internal input lag in OpenGL](https://github.com/twinaphex/ppsspp/issues/25)

- It works correctly in d3d11 but there is a [fallback problem to glcore](https://github.com/libretro/RetroArch/issues/9774)

This update will bring all the new commits to libretro and hopefully fix those problems :)

**Comment by klepp0906** [comment]
watching this, as i just noticed the glcore problem when trying to dive deeper into #9773 

then i remembered having ran into it in the past and saw your reference.  for a minute i thought ppsspp core didnt have vulkan support for some reason.

**Comment by bslenul** [comment]
Oh, I missed this issue! Weird that there's no Libretro issues board for that core 🤔 

A few days ago I posted an issue in upstream: https://github.com/hrydgard/ppsspp/issues/12893

I usually don't do that but like I said in my reply, there's no issues board on Libretro repo + I saw a "Libretro" tag in some issues so I thought maybe some of the contributors worked on the core as well or something.

Anyway, someone was kind enough to still read the issue and made a possible fix: https://github.com/hrydgard/ppsspp/pull/12895

And as gouchi mentioned in the PR comments, the buildbot went further, so yeah... progress I guess :p Now let's hope the new compilation errors are easy to fix 😅 And maybe we'll get an up-to-date core soon for Windows \o/

**Comment by ner00** [comment]
The Windows build of the PPSSPP libretro core seems as if abandoned. There haven't been new builds in the past 8 months or so, essentially keeping Windows-based platforms users isolated from tons of progress and fixes done to the emulator in the past few months. As far as I can see Linux and other platforms have had recent builds, is the problem Windows-only?

**Comment by twinaphex** [comment]
We need a new dedicated maintainer for this core, the current upstream-friendly approach really isn't working out and there are still tons of issues left unresolved in the libretro port. This needs to become a port that treats libretro as a first-class citizen instead of an afterthought.

**Comment by ner00** [comment]
> We need a new dedicated maintainer for this core, none are forthcoming.

I was guessing that this was the case, unfortunately. Well, I hope someone capable eventually comes along to give a hand. Thanks for clarifying the situation.

**Comment by gouchi** [comment]
This is issue should be closed as [buildfixes](https://github.com/hrydgard/ppsspp/commit/649f12f8ab8bd633dce35e400dccdbee41059319) have been provided upstream. Libretro buildbot now has new updated core.

Thank you.

**Comment by Immersion95** [comment]
Should I close this ?

The core is built with the latest commits but :

The core still fallbacks to GLcore when anything else is selected, I have to force it by disabling "Allow cores to switch the video driver".

No video driver solves the problem with Vampire Chronicles which is flawless in standalone. I think standalone switches to software rendering for that game.

**Comment by ner00** [comment]
> Should I close this ?
> 

Personally, I would close this issue and open another one targeted at the specific issues you mentioned.

**Comment by Immersion95** [comment]
I would like to close this but I can't open an issue on the libretro/ppsspp github.

**Comment by gouchi** [comment]
Because [Libretro support has been added upstream](https://github.com/hrydgard/ppsspp/issues?q=is%3Aopen+is%3Aissue+label%3ALibretro).
