### ISSUE TITLE
Retroarch linux (Debian 10) freeze

### ISSUE THREAD

**Issue by benyamin39** [libretro/libretro-super#1338]
Hi,

I have compiled retroarch and the fbneo core following the indication in the docs section below

https://docs.libretro.com/development/retroarch/compilation/linux-and-bsd/

So far no problem at all and retroarch launch perfectly.

Yet the program will freeze if I go to Core Updater menu.

I have recompiled retroarch in debug mode and attached the dbg output (this is the first time I compile in debug mode and report an issue on github, so I may have missed some for in my reporting).

The computer is a Samsung RV420 with Debian 10 Live installed on the harddisk.

I have done the exact same install on a DELL laptop E4310 without any issue at all. So I believe this issue is hardware related. 

Thx

benyamin39

Starting program: /home/benjamin/retroarch/usr/local/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff31f2700 (LWP 9568)]
[Detaching after fork from child process 9572]
[New Thread 0x7fffeb743700 (LWP 9595)]
[CDROM] Could not open /dev/sg0, please check permissions.
^C
Thread 1 "retroarch" received signal SIGINT, Interrupt.
__lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
103	../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) quit
A debugging session is active.

	Inferior 1 [process 9564] will be killed.

Quit anyway? (y or n) y

**Comment by hizzlekizzle** [comment]
Are you sure it's actually frozen and not just waiting for the cores list? That is, a network/server connectivity issue? If you hit backspace a few times, does the menu go crazy?

**Comment by benyamin39** [comment]
It is actually frozen. If I pass a window over the retroarch window it would backen the window like a paintbrush.

Key input does not work (backspace or esc)

Connectivity is ok (i can download assets, cheats,... Note that  often the download stop and the program freeze the same way)

**Comment by RobLoach** [comment]
I think this is fixed.... Also, should likely live in the RA queue rather than libretro-super.

**Comment by gouchi** [comment]
@benyamin39 Please close this issue.

**Comment by gouchi** [comment]
@fpscan Please close this issue.
