### ISSUE TITLE
Wii U PS1 DYNAREC

### ISSUE THREAD

**Issue by captainbk** [libretro/libretro-super#1413]
Just a suggestion for a starting point. Virtual Game Station from Connectix had an incredibly fast recompiler. Mac OS at that point was using G3s, which are the precursors to the Wii U processor. Mac programs and files from that era are extremely easy to access the resources for, so it may be simpler than usual to pull the code.

By releasing a free PS1 Emulator officially, Sony's legal position would seem to support the use of resources from any emulator they own, and Sony owns Virtual Game Station after purchasing from Connectix.

**Comment by hizzlekizzle** [comment]
There's no legal way for us to benefit from that software, unfortunately.
