### ISSUE TITLE
Proper build options for BSD targets

### ISSUE THREAD

**Issue by Menelkir** [libretro/libretro-super#1426]
Without any modification, libretro-build.sh fail to detect compilers for bsd hosts (tested with FreeBSD). It works fine if I export the proper CC, CXX, CXX11, CXX17 and STRIP variables inside libretro-build.sh

For instance, this is the right variables for FreeBSD:

CC=cc
CXX=c++
CXX11=c++
CXX17=c++
STRIP=strip

I can provide a patch, but I'm not sure the proper way to add this inside libretro-build.sh.

**Comment by negativeExponent** [comment]
`$ CC=cc CXX=gcc ./libretro-build.sh `
