### ISSUE TITLE
Vice cores all have the same core name

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/libretro-super#1435]
All of the vice-derived cores all have the same VICE corename. Is this intentional? Does it cause (or solve) any problems?

@sonninnos @rsn8887

**Comment by sonninnos** [comment]
I have no idea where corename is even used, but sure seems reasonable that systemname is appended there.

**Comment by hizzlekizzle** [comment]
Yeah, I'm not 100% sure where it is used, either. I guess pinpointing that would be a good idea...
