### ISSUE TITLE
SameBoy confusion, Buildbot or Master?

### ISSUE THREAD

**Issue by RokkumanX** [libretro/libretro-super#1443]
Hi

I recently updated the Libretro SameBoy core to the latest version and obviously I committed to the Master branch by the looks of it.

However the default branch selected in Libretro/SameBoy is buildbot which doesn't show the changes made, how is this going to work? And the recipe is looking like this:

_sameboy libretro-sameboy https://github.com/libretro/SameBoy.git **buildbot** YES GENERIC Makefile libretro_

It points to buildbot and not Master.

I really want to try the latest SameBoy out but I'm not sure I can?

Will my changes make it to the buildbot?

Thanks in advance!

**Comment by hizzlekizzle** [comment]
I have updated the buildbot branch, so we should be good now, I think. If it doesn't build soon, feel free to reopen.

**Comment by RokkumanX** [comment]
Thanks man!

Seems like the x86 version of the core have been built at the moment, hopefully the x86_x64 will kick in soon.
If nothing is built this day I'll come back and post it here (I can't reopen since you closed)

**Comment by RokkumanX** [comment]
OK, everything is good.

Thanks again for everything!
