### ISSUE TITLE
How i download yabashanshiro core?

### ISSUE THREAD

**Issue by inukaze** [libretro/libretro-super#1475]
Hi there i want to download and compile the Yabasanshiro core?

`git clone https://github.com/libretro/yabasanshiro`

does not work xD because that is not the repository

**Comment by inukaze** [comment]
Well i am trying to do : 

```
echo 'Solve gtkext deps' :
slpkg -s sbo gtkglext gtkglextmm ; ldconfig
```


```
echo 'Download the yabause core'
git clone https://github.com/libretro/yabause ; cd yabause
mkdir build ; cd build
cmake ..
```

13-10-2020 | 08:12 am ]
[build]$ `cmake ..`

> -- The C compiler identification is GNU 5.5.0
> -- The CXX compiler identification is GNU 5.5.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Doxygen: /usr/bin/doxygen (found version "1.8.9.1") found components: doxygen dot 
> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Performing Test VARIADIC_MACROS_OK
> -- Performing Test VARIADIC_MACROS_OK - Success
> -- Looking for gettimeofday
> -- Looking for gettimeofday - found
> -- Looking for floorf
> -- Looking for floorf - found
> -- Looking for _wfopen
> -- Looking for _wfopen - not found
> -- Looking for strcasecmp
> -- Looking for strcasecmp - found
> -- Looking for stricmp
> -- Looking for stricmp - not found
> -- Performing Test BSWAP16_OK
> -- Performing Test BSWAP16_OK - Success
> -- Performing Test BSWAP32_OK
> -- Performing Test BSWAP32_OK - Success
> -- Looking for sys/time.h
> CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
>   Policy CMP0075 is not set: Include file check macros honor
>   CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   CMAKE_REQUIRED_LIBRARIES is set to:
> 
>     -lm
> 
>   For compatibility with CMake 3.11 and below this check is ignoring it.
> Call Stack (most recent call first):
>   src/CMakeLists.txt:178 (check_include_file)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Looking for sys/time.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Found OpenGL: /usr/lib64/libGL.so   
> -- Found GLUT: /usr/lib64/libglut.so  
> CMake Warning at src/CMakeLists.txt:209 (message):
>   Deprecated Glut found.  Support will be removed in the future.
> 
> 
> -- Looking for glXGetProcAddress
> -- Looking for glXGetProcAddress - found
> -- Found GLEW: /usr/include  
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.so;-lpthread  
> -- Found OpenAL: /usr/lib64/libopenal.so  
> -- CMAKE_SYSTEM_NAME Linux
> -- CMAKE_SYSTEM_PROCESSOR x86_64
> -- Looking for linux/joystick.h
> -- Looking for linux/joystick.h - found
> -- Performing Test LINUX_CDROM_H_OK
> -- Performing Test LINUX_CDROM_H_OK - Failed
> -- Performing Test COMPILER_SUPPORTS_CXX11
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
> -- Performing Test CXX11_ERASE_CONST
> -- Performing Test CXX11_ERASE_CONST - Failed
> -- The compiler /usr/bin/c++ doesn't have enough C++11 support. Dynarecs disabled.
> -- Found GTK2_GTK: /usr/lib64/libgtk-x11-2.0.so  
> -- Found OpenGL and Gtk+ but not libgtkglext, skipping Gtk+ port.
> -- Qt5 Found
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /media/2Compartir/zzz_cdf/git/RetroArch/cores/yabause/yabause/build

Well i don't understand why the messages (someone know how fix it?) :

1) 

> CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
>   Policy CMP0075 is not set: Include file check macros honor
>   CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
>   details.  Use the cmake_policy command to set the policy and suppress this
>   warning.
> 
>   CMAKE_REQUIRED_LIBRARIES is set to:
> 
>     -lm
> 
>   For compatibility with CMake 3.11 and below this check is ignoring it.
> Call Stack (most recent call first):
>   src/CMakeLists.txt:178 (check_include_file)
> This warning is for project developers.  Use -Wno-dev to suppress it.

2) 

> -- Found OpenGL and Gtk+ but not libgtkglext, skipping Gtk+ port.

```
echo 'Compile' : 
make
```

echo 'Try to test' :
```
cd yabause/build/src/qt
./yabause
```

What senseless is this?

i don't have SystemD, Avahi, PulseAudio, and i had compile, and pulseaudio is not a Dependecy

why need this lib?

`./yabause: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`

```
cd ../../../src/libretro
make
```

i got **yabause_libretro.so**  core but i just want **yabasanshiro**, where is that core?

**Comment by bslenul** [comment]
For yabasanshiro I believe you have to clone yabause repo and then switch to the yabasanshiro branch.

**Comment by inukaze** [comment]
Hi there, i got the answer when i make this post -> https://github.com/libretro/yabause/issues/229

**Comment by gouchi** [comment]
@inukaze please close this issue.
