### ISSUE TITLE
Sega Saturn Emulation

### ISSUE THREAD

**Issue by inukaze** [libretro/libretro-super#1476]
Hi there again, i had some troubles emulating Sega Saturn with the cores
some days ago i had posted i can use anymore "YabaSanShiro" and i ask ["How i download & Compile Yabasanshiro"](https://github.com/libretro/yabause/issues/229)

Well right now i am trying with another cores like "Kronos" well is 51% more slow than Yabasanshiro but works.

Dunnos with all cores use "Bios" can support "Languages"
¿ How i can set by default for all that cores the language is "Spanish" in case they have in the options ?

¿ Why no all that cores have "Auto Frame-Skip" ?

Right now i try to emulate some games for Europe
"FIFA Rumbo al Mundial 98" (Version for Spain / Europe) 

in the terminal i saw the follow output multiples times : 

```
R0 =  00000000	R12 =  00000000
R1 =  FFFF8888	R13 =  00000000
R2 =  FFFFFE10	R14 =  06000FEC
R3 =  FFFFFE15	R15 =  05F47924
R4 =  00000194	SR =   000000F1
R5 =  0600CFC0	GBR =  FFFFFE00
R6 =  E0000000	VBR =  06000400
R7 [libretro ERROR] Yabause: Slave SH2 invalid opcode
```

Yabause Core Output :
```
R0 =  00000060	R12 =  00000000
R1 =  FFFFFE11	R13 =  00000000
R2 =  FFFFFE10	R14 =  06000FEC
R3 =  FFFFFE15	R15 =  05FCC3FC
R4 =  00000194	SR =   00000060
R5 =  0600CFC0	GBR =  00000000
R6 =  000045E9	VBR =  06000400
R7 [libretro ERROR] Yabause: Slave SH2 invalid opcode
```

Bettle Saturn works with this version of FIFA :D. 
Dunnos with Bettle Saturn 

1 - ¿ Why in the options not exist Auto Frameskip like in Yabasanshiro?

2 - ¿ Why in the options not exist Share Internal Or External Ram with another Cores of Sega Saturn ?

With "Independence Day - The Game" (Europe / Multi 6 / Version 1.000) if i want sound i must enable "Force HLE BIOS" because with the Saturn Saturn BIOS using Kronos i not got any sound / music of game.

with NBA Live 98 

Kronos : 
https://i.postimg.cc/8zZzJkjp/Kronos-NBA-Live-98.png

Bettle Saturn (Mednafen Sega Saturn Module) :
https://i.postimg.cc/HsHY68MW/Bettle-Saturn-NBA-Live-98.png

Well with Panzer Dragoon Saga i guess this in the background its a glitch :
https://i.postimg.cc/7LbYgv2g/Kronos.png

**Comment by RobLoach** [comment]
You'll likely want to make this issue in the bettle core issue queue.

**Comment by inukaze** [comment]
RobLoach with Bettle Core this issue don't exist, just with the another like YabaSanshiro, Yabause & Kronos, happend this issue.

**Comment by gouchi** [comment]
@inukaze please close this issue as it is not related to compilation issue with libretro-super.

Moreover, it will better to ask your questions first on the [forum](https://forums.libretro.com/) or [discord](https://discordapp.com/invite/27Xxm2h) and if there is an issue with the core please open an issue in the repository of the core either [beetle-saturn-libretro](https://github.com/libretro/beetle-saturn-libretro) or [yabause](https://github.com/libretro/yabause).

Thank you.
