### ISSUE TITLE
Unable to build PicoDrive

### ISSUE THREAD

**Issue by maxengel** [libretro/libretro-super#1525]
When running `sudo ./libretro-build.sh picodrive` the core fails to build. The console outputs:
```
make: *** No rule to make target 'pico/cd/libchdr/src/libchdr_chd.o', needed by 'picodrive_libretro.so'.  Stop.
make: *** Waiting for unfinished jobs....
cp "picodrive_libretro.so" "/home/$user/Gaming/Cores/libretro-super/dist/unix/picodrive_libretro.so"
cp: cannot stat 'picodrive_libretro.so': No such file or directory
```

**Comment by negativeExponent** [comment]
- why would you want to "sudo" to compile?
- you did not pulled submodules

**Comment by maxengel** [comment]
@negativeExponent I've had issues compiling when not using `sudo`.

Do you have a link to the documentation around which submodules I should pull?

Thanks!

**Comment by m4xw** [comment]
libretro-super is deprecated, also not even lr super related
