### ISSUE TITLE
missing info files (fbalpha_libretro.info and minivmac_libretro.info)

### ISSUE THREAD

**Issue by ReenigneArcher** [libretro/libretro-super#1565]
Two cores in the build bot are missing info files (at least for Windows x86_64)

https://buildbot.libretro.com/nightly/windows/x86_64/latest/fbalpha_libretro.dll.zip

https://buildbot.libretro.com/nightly/windows/x86_64/latest/minivmac_libretro.dll.zip

My understanding is that fbalpha_libretro was replaced by fbneo_libretro, if so fbalpha should probably be taken off the build bot? Or info file should be created for it.

I may make an attempt at creating the info files, just not sure what features each core has.

**Comment by RobLoach** [comment]
Fixed by https://github.com/libretro/libretro-super/pull/1587
