### ISSUE TITLE
./libretro-build-ios9.sh and ./libretro-build-ios10.sh fail to compile cores

### ISSUE THREAD

**Issue by don17sch** [libretro/libretro-super#1567]
I am trying to compile these cores on Mac and am getting the following error on all cores

clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]

I am running on the latest version of macOS as of today 11.5.2 and on the M1 chip

has the script been updated to work on newer versions of macOS

**Comment by don17sch** [comment]
closing this as I found out via trial and error that ios using a new script other than these 2

**Comment by lucaurso** [comment]
do you mind explaining which script do we need for ios 15?

**Comment by Donald-Schickel-Aspiritech** [comment]
> 

https://github.com/libretro/libretro-super/blob/master/libretro-build-ios-arm64.sh

**Comment by lucaurso** [comment]
thanks! I was testing exactly that right now as I checked the architecture of my ipad pro

**Comment by don17sch** [comment]
https://github.com/libretro/libretro-super/blob/master/libretro-build-ios-arm64.sh

**Comment by don17sch** [comment]
sorry for the delete repost I posted that with a work account by accident
