### ISSUE TITLE
[Request] Offer Minimal RetroArch Builds for Windows

### ISSUE THREAD

**Issue by Awakened0** [libretro/libretro-super#1581]
I'm not sure if many users besides me would like this, but I think it'd be nice to have a minimal RA Windows package with a few features that require many .dll dependencies disabled. Primarily FFMPEG and qt. I imagine there are many users who don't use video/audio file playback or the desktop menu, and those require the most .dlls. I'd be open for suggestions for other lesser used features that would make the .exe smaller and/or remove .dlls.

When I've done my own minimal builds, I've disabled all this stuff:
`./configure --disable-overlay --disable-networking --disable-video_filter --disable-video_layout --disable-glsl --disable-bsv_movie --disable-dsp_filter --disable-cheats --disable-rewind --disable-accessibility --disable-translate --disable-cdrom --disable-imageviewer --disable-qt --disable-ffmpeg --disable-sdl2 --disable-blissbox --disable-xmb --disable-materialui --disable-rgui --disable-d3d9 --disable-d3d10 --disable-wasapi --disable-libretrodb --disable-audiomixer --disable-dsound --disable-flac --disable-dr_mp3 --disable-rtga --disable-rjpeg --disable-rbmp --disable-freetype --disable-langextra --disable-cc_resampler --disable-nearest_resampler --disable-crtswitchres --disable-chd --disable-7zip --disable-patch`

That's probably going too far since most of those probably only remove a few kb from the .exe at most. Maybe SDL2, since it's .dll is one of the largest at 10MB. If you do go that hard with disabling features you get a very small (6.6MB) exe with just three .dlls.

A more conservative, but still effective at reducing dependencies ./configure set would be simply:
`./configure --disable-qt --disable-ffmpeg --disable-sdl2`

If a minimal download is made available, the unavailable features could just be added in parenthesis next to it, ie (audio/video file playback and desktop menu disabled). If it's too much strain on the buildbot, it could only be made for point releases, but I'd love to have minimal nightlies too. Not sure if Linux or other OS's would be worth having minimal builds too since dependencies are different there, I think.

**Comment by RobLoach** [comment]
Being a minimalist myself, I very much appreciate taking a minimal approach. RetroArch likely will not distribute this however, as it could confuse users. That doesn't mean you can't create your own GitHub repository with information about this script and what it accomplishes :wink:

**Comment by hizzlekizzle** [comment]
I believe we had discussed at some time changing the organization of the Windows release to put the executable and libs into a subdir with a launcher shortcut instead of just dumping everything at the top level, if the goal is to avoid the mess. (it's how I organize my installation in Windows)

**Comment by Awakened0** [comment]
> RetroArch likely will not distribute this however, as it could confuse users.

I was thinking it could be listed under "List of Supported Platforms", "Windows 11 / 10 / 8 / 7" as something like "Download (64bit) Mini" like how Notepad++ has a Mini build on their [download page](https://notepad-plus-plus.org/downloads/v8.1.9.3/). Actually, it'd be better if those links were renamed from "Download" to "Portable" to indicate they're portable zip archives. Anyways, I figure users scrolling down to those links have more of an idea of what they want than those that just click the big Nightly or Stable installer links at the top.

> I believe we had discussed at some time changing the organization of the Windows release to put the executable and libs into a subdir with a launcher shortcut instead of just dumping everything at the top level, if the goal is to avoid the mess. (it's how I organize my installation in Windows)

That would definitely make the directory look nicer. But you also save a nice chunk of space (nightly exe + dlls are like 143MB vs 8.3MB for my non-conservative minimal build). It also makes it so you have less stuff to hide in the menus than a full fat build.

**Comment by Awakened0** [comment]
Maybe instead of offering minimal builds through the website/buildbot, they could be done with github actions. It doesn't look like any artifacts are available on the RetroArch repo's Actions page though. It's probably beyond me to get those set up.

**Comment by hizzlekizzle** [comment]
Yes, that's certainly doable via github actions. If you want to try it, I made a nightly recipe awhile back that you can start with: https://github.com/hizzlekizzle/RetroArch-AppImage/blob/master/.github/workflows/nightly_win_lin.yml#L120

**Comment by Awakened0** [comment]
Thanks for the starting point! This is where I'm at now: https://github.com/Awakened0/RetroArch-Minimal-Builds/blob/main/.github/workflows/nightly_win_minimal.yml

But I can't figure out why it's not including the .dll files in the 7z file, only the .exe.

**Comment by Awakened0** [comment]
Did some more editing and got it to include the .dll's, though the way I'm doing it includes nvdaControllerClient64.dll and I haven't been able to get it to exclude.

**Comment by Awakened0** [comment]
It's easy to trigger builds for me now, so I'll close this. If there's any interest in adding minimal builds to the upstream RetroArch repo it'd be easy to pull my script. But it'd probably have to be fleshed out a bit, like including assets in the archives, for an official release.
