### ISSUE TITLE
Easyrpg recipe for Linux (x64) is obsolete

### ISSUE THREAD

**Issue by tannisroot** [libretro/libretro-super#1583]
```
buildbot job: building easyrpg
BUILD CMD: make -f Makefile.libretro platform=unix -j16
make: Makefile.libretro: No such file or directory
make: *** No rule to make target 'Makefile.libretro'.  Stop.
```
It wants a Makefile.libretro file that isn't there anymore. From what I can see, the build system moved to cmake, so the recipe needs to be updated to that perhaps (I dabbled a bit myself but it still doesn't want to build).

**Comment by m4xw** [comment]
libretro-super is deprecated

**Comment by tannisroot** [comment]
Is there a new replacement for it?

**Comment by Ghabry** [comment]
@tannisroot 
For easyrpg player see the Libretro section of the readme https://github.com/easyrpg/player

Is a normal CMake build
