### ISSUE TITLE
Add a deprecation notice

### ISSUE THREAD

**Issue by tannisroot** [libretro/libretro-super#1584]
https://github.com/libretro/libretro-super/issues/1583#issuecomment-976373840

**Comment by RobLoach** [comment]
For EasyRPG, to allow it to build with libretro-super, we'd need to update the recipe to use cmake. Something like this:
```
easyrpg libretro-easyrpg https://github.com/EasyRPG/Player.git master YES CMAKE Makefile builddir
```

**Comment by tannisroot** [comment]
I believe I edited more or less like this and easyrpg was complaining that it couldn't find an include, which it has in its include directory. I think? easyrpg cmake script assumes that it's build built from the repo directory (and I guess it's not with libretro-super?) and this is breaking it.
