### ISSUE TITLE
Philips CD-i Core

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-super#1621]
With MAME .239, the CD-i emulation has been improved quite a bit.  I've created a new core, based on mame_libretro, which compiles only the cdi driver, and then hard codes and handles loading the game file directly, without all the claptrap needed in regular MAME commands or softlist setups.
https://github.com/zach-morris/same_cdi

[Info file](https://github.com/zach-morris/same_cdi/blob/main/same_cdi_libretro.info)

The core currently accepts CHD and ISO game files.  It would also accept BIN/CUE but there's an open issue in MAME currently for support of the CDI BIN/CUE format.

The core has been tested in OSX and windows and seems to work just fine.  I haven't tested it in linux or android, but I assume it builds just the same as the regular MAME core does.  I currently is only missing the gitlab-ci.yml that was included in the mame_libretro repository, as I'm sure that would need to be reconfigured anyway.

At any rate, I'm not sure what the official means of submitting a core for consideration into libretro is, but same_cdi is available to be forked into the project if you find it to be good to go.

Semi-related, there may be a few other systems that would benefit from the same single driver treatment:
FM Towns
PC-98 CD
etc

**Comment by jdgleaver** [comment]
@zach-morris I just noticed your new core - this is excellent work, very much appreciated!

I am sorry that it's been ignored for so long (indeed, the means for submitting a core is somewhat ad-hoc, and relies on the right people seeing it...), but I shall endeavour to get it integrated with our build infrastructure in the next few days. I will keep you posted :)

**Comment by jdgleaver** [comment]
@zach-morris We have a fork of your repo here: https://github.com/libretro/same_cdi, and everything is set up on the buildbot. Binaries should be available by tomorrow. Many thanks again for your work!

**Comment by zach-morris** [comment]
Ah good deal!  Thanks for taking a look.  I'll see how it works
