### ISSUE TITLE
PPSSPP: failed to open libretro core

### ISSUE THREAD

**Issue by Vagankovo** [libretro/libretro-super#1641]
Operating system: Linux (Arch Linux)
## The problem
RetroArch cannot run the PPSSPP core. Logs in verbose mode show this:
```
[ERROR] Failed to open libretro core: "/usr/lib/libretro/ppsspp_libretro.so"
[ERROR] Error(s): /usr/lib/libretro/ppsspp_libretro.so: undefined symbol: _ZN10BinManager18MAX_POSSIBLE_TASKSE
```
Either Arch maintainers forgot to add in a dependency, or something is wrong in the codebase

**Comment by RobLoach** [comment]
Close this one. Make an issue in the PPSSPP. THis is not a support forum.
