### ISSUE TITLE
libretro core for the ONScripter visual novel engine

### ISSUE THREAD

**Issue by iyzsong** [libretro/libretro-super#1642]
Hello, I have a somehow working onscripter libretro core: https://github.com/iyzsong/onscripter-libretro

And I have some questions:
1. Now valid_extensions is `txt|dat|___` as a onscripter game is usually a folder with `nscrpit.dat` or `pscript.dat` or `0.txt`, the filename is fixed.  Can retroarch load directory (not file) as game?  Or should I make a new extension `.ons` then it can display a nicer name like `my-game.ons`?

2. Now having 2 submodules for `tinycoroutine` and `libretro-common`, while other deps (see `deps.scm`) are fetching via a `update-deps.sh` script.  Should I commit those deps (bzip2, freetype, sdl, onscripter, etc.) into the repository?

3. And any chance or todos to get it upstream into the updater?

Thank you!

**Comment by hizzlekizzle** [comment]
1. making a new extension certainly works. You could also support zips of the directories (using zlib, if you don't mind another dep).
2. we usually recommend having libretro-common copied into the repo (and just the subset of files you actually use/need, at that), but yes, we typically try to go ahead and vendor any deps whenever possible.
3. I don't see any reason why not :)

**Comment by iyzsong** [comment]
I have upload the external dependiences pack tarball to a github release, and now `update-deps.sh` will download and unpack it.

Should I create a PR for include onscripter core in libretro-super?
I only tested it on Linux amd64 so far..

**Comment by hizzlekizzle** [comment]
ah, that's great!

Yes, you can start there, and after that we can see about getting it into the online updater @LibretroAdmin

**Comment by iyzsong** [comment]
I open a PR #1710 now, this can be closed, @hizzlekizzle  thank you!
