### ISSUE TITLE
Numero Core

### ISSUE THREAD

**Issue by nbarkhina** [libretro/libretro-super#1707]
Hi Libretro Team, 

I had developed a new core called Numero which emulates the TI-83 calculator and was hoping would it be possible to submit it to the Online Updater so people could download it from RetroArch? What is the process to submit a core for buildbot? I had followed the instructions on this page [developing-cores](https://docs.libretro.com/development/cores/developing-cores/) and had submitted to the super/docs repos which have already been merged but I don't seem to find it in either the online updater or in the buildbot pipelines. I do see it as part of the documentation here [docs](https://docs.libretro.com/library/numero/) which is really cool! 

Here is the repo link -

https://github.com/nbarkhina/numero

I created a [gitlab-ci.yml](https://github.com/nbarkhina/numero/blob/master/.gitlab-ci.yml) and [info file](https://github.com/libretro/libretro-super/blob/master/dist/info/numero_libretro.info). The system requirements for the core are pretty low and it doesn’t use any hardware acceleration so it should be able to run in most places - windows, android, emscripten, etc… please let me know if there is anything else I need to do. 

Thanks!

**Comment by fpscan** [comment]
@RobLoach @hunterk could you kindly help @nbarkhina to add his core to buildbot? I have tried on windows and it runs fine.

**Comment by nbarkhina** [comment]
yes closing thanks!
