### ISSUE TITLE
pcsx2 no longer compiles due to missing target

### ISSUE THREAD

**Issue by Shoegzer** [libretro/libretro-super#1757]
As the title implies.  Even once #1756 is merged, pcsx2 core will still not compile as the CMake flag `LIBRETRO=ON` is no longer recognized, and there is no longer a target for libretro_pcsx2 as there used to be.

Build log excerpt:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    LIBRETRO


-- Build files have been written to: /home/testing/Desktop/retroarch/libretro-super/libretro-pcsx2/build
BUILD CMD:  cmake --build . --target pcsx2_libretro --config Release -- -j  16
gmake: *** No rule to make target 'pcsx2_libretro'.  Stop.
```
Full build log: [build.log](https://github.com/libretro/libretro-super/files/12601121/build.log)

**Comment by zoltanvb** [comment]
Just FYI: unfortunately, pcsx2 upstream does not support libretro target, and it is not very likely to change. The libretro-pcsx2 branch is dead, another replacement / hard fork was started as https://github.com/libretro/LRPS2 but it has also not seen updates since a while - anyway I believe that is the one that is currently being compiled on e.g. buildbot, with the old binary name pcsx2.

**Comment by hizzlekizzle** [comment]
The 'libretro' branch of https://github.com/libretro/pcsx2 is a rebase from circa May of this year, and some people have been using it successfully (see here: https://forums.libretro.com/t/new-pcsx2-core/41170/19).

**Comment by Shoegzer** [comment]
@hizzlekizzle Yup, I've been building the "official" libretro core as it's more up-tp-date than the LRPS2 fork.  However, still running into the issue I mentioned above.  If you have any suggestions to get it working I'd love to hear them and can add them to the PR if they work out.

**Comment by zoltanvb** [comment]
The "libretro" git branch seems to have that missing target.

**Comment by Shoegzer** [comment]
You're right, I guess I missed that since most other cores build under the "master" branch.  Updated PR #1756 and now the core will build fine once it gets merged. Thanks, closing.
