### ISSUE TITLE
melonDS DS missing, cannot be built

### ISSUE THREAD

**Issue by DJtheMan2101** [libretro/libretro-super#1801]
It looks like the [melonDS DS](https://github.com/JesseTG/melonds-ds) core is missing from [core-rules.sh](https://github.com/libretro/libretro-super/blob/master/rules.d/core-rules.sh), so it cannot be built from libretro-super. It has to be built from its source repo. For some reason, it never got added here even after it was released on the buildbot. Having it here would be pretty convenient, since all the cores could be built from one place.

**Comment by RobLoach** [comment]
Thanks. This can be closed.
