### ISSUE TITLE
RetroArch missing Start Core entry

### ISSUE THREAD

**Issue by lauren7ino** [libretro/libretro-super#1807]
Hello
Sorry my basic English, is not my mother language.

Can please you provide information how can I start fuse_libretro in RetroArch in the Spectrum Basic, without loading any game?

I'm using RetroArch 1.10.0 and Fuse 1.6.0, in ArkOS in an Anbernic RG353M console.

The problem it seems is that after I tell RetroArch to load the Fuse Core,
Fuse is not adding the option "Start Core" to the main menu of Retro Arch.

Other cores like the C64 core add the "Start Core", but fuse doesn't.

I've reported this in ArkOS issues, but the developer says it's a core problem, and he can not do anything about this.

Thank you

**Comment by zoltanvb** [comment]
It is depending on the core. I see you have opened it in the correct place:
https://github.com/libretro/fuse-libretro/issues/141
This issue here can be closed.

**Comment by gouchi** [comment]
@fpscan @LibretroAdmin Please close this issue. Thank you.
