### ISSUE TITLE
Missing a README with a simple howto

### ISSUE THREAD

**Issue by mamoit** [libretro/libretro-super#229]
I bumped into this project yesterday, and before I could start compiling I had to do a lot of googling since there was no README around here.
It would be a nice thing :smile:

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-super/pull/249

**Comment by RobLoach** [comment]
Recommend closing this, as we now have a makefile to help building, along with some more docs.  Feel free to open up a new issue if it's not clear. Thanks.

**Comment by mamoit** [comment]
:+1: Makes sense.
The other issue is more comprehensive also.
