### ISSUE TITLE
Extensions in Mupen64plus .info file don't match retro_system_info

### ISSUE THREAD

**Issue by Alcaro** [libretro/libretro-super#242]
https://github.com/libretro/mupen64plus-libretro/blob/master/libretro/libretro.c#L363 says n64|v64|z64.

https://github.com/libretro/libretro-super/blob/master/dist/info/mupen64plus_libretro.info says n64|v64|z64|bin|u1.

I do believe these lists are supposed to match each other. I could change this myself, but I'd rather poll for consensus on which version is correct first. (I prefer the system_info version because I've never seen a u1, and bin can belong to dozens of different systems.)

**Comment by lasers** [comment]
Welcome to 2016. 
```
libretro.c:691:   info->valid_extensions = "n64|v64|z64|bin|u1|ndd";
mupen64plus_libretro.info:supported_extensions = "n64|v64|z64|bin|u1|ndd"
```
Close this?
