### ISSUE TITLE
Minor core title misspellings

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/libretro-super#246]
Some of the core names are spelled inaccurately. This is what I've found, probably have missed some nightly-only cores: 
bNES -> bnes, DeSmuME svn -> DeSmuME (SVN), dosbox -> DOSBox, gambatte -> Gambatte, handy -> Handy, Mednafen Neopop -> Mednafen NeoPop, Mupen64plus -> Mupen64Plus, prboom -> PrBoom
EDIT: Most of these seem to only be misspelled only in the names that are shown before version on the bottom of the screen, the ones in the Info section are often fine.

**Comment by Oggom** [comment]
Technically this is an issue within the cores themselves ("info->library_name" within the libretro.c files).
I'll take a look at them.

**Comment by GeneralFailer** [comment]
I know, Alcaro said this is an appropriate repo in libretro/snes9x#11. Besides, opening 8 different issues about this would be suboptimal. :) 
Thanks, this can be closed now.
