### ISSUE TITLE
telling ./retroarch-build.sh a location where to put binary?

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/libretro-super#248]
What arguments can I specify to dump the retroarch binary to launch Retroarch, short of symlinking it?

Thanks

**Comment by chaoskagami** [comment]
After looking through the Makefiles, I *think* you want to:
make PREFIX=(location like /usr/games) GLOBAL_CONFIG_DIR=(location like /etc)
make PREFIX=(location like /usr/games) GLOBAL_CONFIG_DIR=(location like /etc) install

Replace the stuff in parenthesis. This *should* work, but I'm also not a developer. This should probably be documented.

**Comment by iKarith** [comment]
In the not too distant future, this should be handled by 
libretro-super.sh.  When it is, I'll be sure it's documented 
properly.  What I need in the mean time is a few moments to actually 
work on stuff.  I've not had much luck on that lately—one thing after 
another.

Joseph

**Comment by chaoskagami** [comment]
That's life, isn't it? Tell me about it. :P
This isn't a gigantic 'makes everything explode with segfaults' bug, anyways. From my perspective, at least. Cores can just be copied and RetroArch built separately.

**Comment by ProfessorKaos64** [comment]
Take your time man, and do it right. I'm just extremely happy I have Retroarch and the libretro cores compiled on SteamOS. Works great!

**Comment by iKarith** [comment]
You can actually have a look at libretro-super.sh right now:

http://github.com/iKarith/libretro-super.git

Feedback is wanted.  One of the major reasons why there is currently 
no support for RetroArch itself in that is that the makefile system 
used to build it is not simple and cohesive.  One way to go a long 
way toward that is for the RetroArch Makefile to eg, recognize when 
it's being run on a Mac, verify Xcode is installed on configure, and 
just call it to compile.

Those kinds of details are supposed to be outside of libretro-super's 
reach, and I'd rather not change that.  But thus far people who've 
looked at the script seem to think it'll be an improvement over what 
we're doing right now.

Anything more than this and I'd need to port it to Ruby or Lua or 
something—and that'd mean libretro-super would need to have an 
interpreter built-in in case the user doesn't have something quite 
suitable.  That's somewhat less than ideal, though.

Joseph

**Comment by ProfessorKaos64** [comment]
Ok, If I get some time this weekend (I am on call for wok so I will be home), i'll tinker with it Joseph. Not sure if I can help, but i'll give it try. I'd love an easier way for my automated script for SteamOS, but the current setup works just fine.

**Comment by twinaphex** [comment]
I will never be prepared to force a dependency like Lua or Ruby on libretro-super btw.

**Comment by iKarith** [comment]
No, it couldn't be a dependency—it'd have to be built-in.  And the 
way libretro-super.sh works, it's probably not necessary.  Bash is 
slightly brain-dead, but it's also pretty powerful.  Did you know it 
can download web pages all on its own?  :)  Pretty easily actually.

Joseph

**Comment by chaoskagami** [comment]
Bash can do pretty much anything, it's just a matter of how many lines you want to write and how confusing and in need of comments it is. ;)

I agree scripting languages are overkill here. Lua would probably need as many lines as bash has now to get things done. It's unecessary.

**Comment by lasers** [comment]
Close this?
