### ISSUE TITLE
Wrongly named configuration option in config file.

### ISSUE THREAD

**Issue by Darksecond** [libretro/libretro-super#256]
In libretro-buildbot-recipe.sh on line 1203 It says `content_database_directory = ":\database\rdb"`. However the configuration option should be named `content_database_path`.

**Comment by lasers** [comment]
Welcome to 2016.

Line 1203 -- Empty line (readability spacing).
`content_database_directory` does not exist anywhere anymore.
`:\database\rdb` does not exist anywhere anymore.
`content_database_path` does not exist anywhere anymore.

Close this?
