### ISSUE TITLE
missig dolphin core in fetch-rule

### ISSUE THREAD

**Issue by CptLausebaer** [libretro/libretro-super#258]
There is no entry for the [dolphin](https://github.com/libretro/dolphin)-core in the `rules.d/core-rules.sh`

**Comment by fr500** [comment]
the core isn't remotely close to working... so, no point

**Comment by RobLoach** [comment]
For those interested, I made a [libretro Dolphin Launcher core](https://github.com/robloach/libretro-dolphin-launcher) as a work around, until the Dolphin core is working.
