### ISSUE TITLE
mame159 fails to build due to failing dependencies

### ISSUE THREAD

**Issue by HorstBaerbel** [libretro/libretro-super#262]
I have Ubuntu 14.04.3 here and did a "libretro-fetch". Then I tried to "libretro-config" and "libretro-build" and 15 cores failed (I had last successfully compiled ~a year ago). I tried to build libretro-mame159 by itself using "make", but it failed due to a lot of zlib *.o files missing. I went to the 3rdparty/zlib subdirectory and did a "./configure --static", built zlib using "make" and copied the .o files to libretro-mame159/obj/sdl64/lib/zlib.  I had to do more or less the same for expat.
Then I gave up on softfloat, as it does not have a MakeFile, CMakeLists.txt or different. "gcc softfloat.c" reports a missing "emu.h". Any hints?
It would be sweet if the libraries would check and report missing dependencies before compiling and failing. I had to install libsdl2-dev and libsdl2-ttf-dev while compiling mame159. Switching to CMake would make that easier, I guess...

**Comment by hizzlekizzle** [comment]
I think libretro-mame is broken right now, so you should use libretro-mame2014 instead (it's the most recent snapshot). In either case, you don't build with just 'make' as that will start using the regular MAME buildchain, IIRC. Instead, use make -f Makefile.libretro.

**Comment by twinaphex** [comment]
libretro-mame should work just fine.

> It would be sweet if the libraries would check and report missing dependencies before compiling and failing. I had to install libsdl2-dev and libsdl2-ttf-dev while compiling mame159. Switching to CMake would make that easier, I guess...

Something tells me you're doing it completely wrong compiling the libretro core if you had to install such dependencies.

Anyway, we will never, ever, ever resort to cmake. We use static Makefiles for a reason.

**Comment by HorstBaerbel** [comment]
I haven't tried with -f Makefile.libretro... What's the difference between the scripts? Also why not only the most recent mame?
libretro-mame does build now though, even using libretro-build.sh, probably after "libretro-fetch"ing again... Maybe builds known to be broken should be excluded from the libretro-build.sh script. Would save some time.

**Comment by twinaphex** [comment]
both mame159 and mame libretro should compile just fine, they do at least for me on Arch Linux.

**Comment by HorstBaerbel** [comment]
I'll try -f MakeFile.libretro when I find time, but "out of the box" (Ubuntu 14.04.03, git clone, libretro-fetch, libretro-build) it didn't work for me.

**Comment by twinaphex** [comment]
You will usually have to run make several times since MAME's build system sucks with circular dependencies at compile time where it needs to generate certain files first before actually being able to compile them, so if you compile with a lot of jobs you might just run into a race issue where it decides to compile a file that does not exist yet because the file that 'generates' it has not been processed yet. Yes it's messy like that. Nothing I can do about it unless I want to take on even more maintenance time, chop up their old Makefiles in MAME 159 and change how it works.

**Comment by HorstBaerbel** [comment]
That might explain it. I usually do a "make -j4"... :/
