### ISSUE TITLE
Writing a core

### ISSUE THREAD

**Issue by leo60228** [libretro/libretro-super#270]
How do I write a core? I can't find any documentation.

**Comment by fr500** [comment]
https://github.com/libretro/libretro.github.com/raw/master/documents/libretro.pdf

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-lutro/ is an easy example as well.

**Comment by RobLoach** [comment]
Recommend either closing this, or re-framing it to write more libretro API documentation.
