### ISSUE TITLE
reicast core is not compiled

### ISSUE THREAD

**Issue by legluondunet** [libretro/libretro-super#279]
Hello,

the libretro-super download the Reicast source core, but does not compile it.
Is it normal?
For the moment I compile and install it manually.
Regards.

**Comment by gouchi** [comment]
Hi,

On which platform ?

**Comment by legluondunet** [comment]
Linux

**Comment by gouchi** [comment]
The core is available on Linux for [i686](http://buildbot.libretro.com/nightly/linux/x86/), [x86_64](http://buildbot.libretro.com/nightly/linux/x86_64/latest/) not [armhf](http://buildbot.libretro.com/nightly/linux/armhf/latest) platform. So you should be able to compile it.

**Comment by legluondunet** [comment]
This bug is obsolete since you can now download whatever module you want from retroarch gui on Linux PC. 
But you didn't explain why  libretro-super script does not automatically compile reicast module.

**Comment by gouchi** [comment]
AFAIK the buildbot is using libretro-super script to compile.

**Comment by orbea** [comment]
The buildbot uses this script.
https://github.com/libretro/libretro-super/blob/master/libretro-buildbot-recipe.sh
