### ISSUE TITLE
Games not loading (stuck on Lakka flower)

### ISSUE THREAD

**Issue by ShockwaveTheFallen** [libretro/libretro-super#337]
Requested background info:

Description of the problem: When trying to Load Content (game), the OS locks up and does not proceed to game and get stuck on the flower screen. Does not proceed anywhere or exit back out to main menu. Have to hard reboot the system. Does this for ALL cores, games, etc. 

Hardware being used: Asus Chromebox CN60 (M004U). Write protection screw removed, 2 GB DDR3 RAM, 16 GB Sandisk M.2 2242 SSD, Chrome OS removed and Lakka installed on SSD. 

Copy of log: 
![2016-09-12 1](https://cloud.githubusercontent.com/assets/22160208/18459648/35b41b06-7920-11e6-9b2c-57cb3b5ce5c7.png)
![2016-09-12 2](https://cloud.githubusercontent.com/assets/22160208/18459649/35b54814-7920-11e6-853a-e0aa08a294dc.png)
![2016-09-12](https://cloud.githubusercontent.com/assets/22160208/18459650/35b55f8e-7920-11e6-892d-f4f2f76ae2cf.png)

Cores used: mupen64plus, SNES9x-2010, FCEuu, Genesis-Plus-GX. 

Lakka version: 1.3.6 (downloaded from website)

**Comment by ShockwaveTheFallen** [comment]
Wanted to update, tried the latest nightly, and still didn't work out. Stuck at the flower screen. Tried both installing from the SSD and from USB Live Mode and same thing.

**Comment by RobLoach** [comment]
I'd suggest moving this discussion over to the Lakka issue queue. May have a better response.

**Comment by lasers** [comment]
Close this?

**Comment by gouchi** [comment]
Yes we should closed as it is not the correct repo and it is expired.
