### ISSUE TITLE
mame android build

### ISSUE THREAD

**Issue by r-type** [libretro/libretro-super#365]
@fr500  can you also add ANDROID_NDK_LLVM  in
cores-android-armv7-ndk-mame.conf , to see how the things goes.

**Comment by r-type** [comment]
Can someone look at the buildbot problem with the core mame 0.179 for windows android?
as they build fine by hand.

**Comment by r-type** [comment]
Ok since no one here have time to add/watch this i will close issue.
But please dont ask me to look at this mame build later.

**Comment by twinaphex** [comment]
@r-type I was not aware of this issue, I will ask radius again.

Also, it would really help if you could visit us on IRC freenode at #retroarch for development purposes and to talk about things, things can often get lost or ignored when talking only on github.

**Comment by r-type** [comment]
btw , recent ndk13 change to libretro-super  
 make: arm-linux-androideabi-g++: Command not found
should be
PATH /home/buildbot/tools/android/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin
instead of 
PATH /home/buildbot/tools/android/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 ?

**Comment by fr500** [comment]
@r-type I've been busy sorry about it
You're right we're missing ANDROID_NDK_LLVM, what should I set it too?

http://hastebin.com/zayilugiva

This is for 2014
http://hastebin.com/vozekekeno

**Comment by r-type** [comment]
for mame , seem it always missing  ANDROID_NDK_LLVM in
cores-android-armv7-ndk-mame.conf
makefile:1072: *** ANDROID_NDK_LLVM is not set.  Stop.

for 2014 , did you build with an standalone toolchain ?

**Comment by fr500** [comment]
both are using the standalone toolchain yes.
What should I set ANDROID_NDK_LLVM to?

**Comment by r-type** [comment]
yes it should be set even if useless after, else stupid makefile rule will failed .
see  android-ndk rule (makfile line 1070) called by android-arm (line1092)

for mame2014 , strange I have just build using standalone tc generated with android-ndk-r13b
using 
```
make -f Makefile platform=android -j6 TARGET=mame
```
and it build fine.
exept minor change to makefile for correcting place 
```diff --git a/Makefile b/Makefile
index 010ea9a..6351247 100644
--- a/Makefile
+++ b/Makefile
@@ -679,9 +679,9 @@ OBJDIRS = $(OBJ) $(OBJ)/$(TARGET)/$(SUBTARGET)
 
 ifneq ($(TARGETOS),emscripten)
 LIBEMU = $(OBJ)/libemu.a
-LIBOPTIONAL = $(OBJ)/$(TARGET)/$(TARGET)/liboptional.a
-LIBDASM = $(OBJ)/$(TARGET)/$(TARGET)/libdasm.a
-LIBBUS = $(OBJ)/$(TARGET)/$(TARGET)/libbus.a
+LIBOPTIONAL = $(OBJ)/$(TARGET)/$(SUBTARGET)/liboptional.a
+LIBDASM = $(OBJ)/$(TARGET)/$(SUBTARGET)/libdasm.a
+LIBBUS = $(OBJ)/$(TARGET)/$(SUBTARGET)/libbus.a
 LIBUTIL = $(OBJ)/libutil.a
 LIBOCORE = $(OBJ)/libocore.a
 else
@@ -696,7 +696,7 @@ endif
 LIBOSD =  $(OBJ)/osd/retro/libretro.o $(OSDOBJS)
 
 VERSIONOBJ = $(OBJ)/version.o
-EMUINFOOBJ = $(OBJ)/$(TARGET)/$(TARGET).o
+EMUINFOOBJ = $(OBJ)/$(TARGET)/$(SUBTARGET).o
 DRIVLISTSRC = $(OBJ)/$(TARGET)/$(SUBTARGET)/drivlist.c
 DRIVLISTOBJ = $(OBJ)/$(TARGET)/$(SUBTARGET)/drivlist.o
```

**Comment by fr500** [comment]
yes but set to what?
ANDROID_NDK_LLVM = ????

what value should I use?

**Comment by r-type** [comment]
https://github.com/libretro/mame/blob/master/src/osd/libretro/libretro-internal/README.MD

something like
```
export ANDROID_NDK_LLVM="/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64" 
export ANDROID_NDK_ARM="/opt/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64" 
export ANDROID_NDK_ROOT="/opt/ndk"

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 NOASM="1" gcc="android-arm" OS="linux" TARGETOS="android-arm" CONFIG=libretro NO_USE_MIDI="1" TARGET=mame -j4
```

**Comment by fr500** [comment]
Thanks I'll try to figure it out now

**Comment by fr500** [comment]
so this should be fine I guess? ANDROID_NDK_LLVM /home/buildbot/tools/android/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64/

That's my toolchain dir

**Comment by fr500** [comment]
BUILD CMD:  make -f makefile platform=android -j6 OSD=retro RETRO=1 NOWERROR=1 NOASM=1 gcc=android-arm gcc_version=4.9 TARGETOS=android-arm CONFIG=libretro NO_USE_MIDI=1 OS
=linux VERBOSE=1 verbose=1 OVERRIDE_CC=/home/buildbot/tools/android/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang OVERRIDE_CXX=/home/buildbot/tools/andro
id/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
GCC 6.2.0 detected
GCC 6.2.0 detected
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
make -R verbose=1 -C 3rdparty/genie/build/gmake.linux -f genie.make
make -R verbose=1 -C 3rdparty/genie/build/gmake.linux -f genie.make

loooooooooooong output


../../../../../src/emu/emu.h:21:10: fatal error: 'list' file not found
#include <list>
         ^
../../../../../src/emu/emu.h:21:10: fatal error: 'list' file not found
#include <list>
         ^
1 error generated.
1 error generated.
precompile.make:515: recipe for target '../../../../libretro/obj/libretro/emu.h.gch' failed
make[2]: *** [../../../../libretro/obj/libretro/emu.h.gch] Error 1
precompile.make:515: recipe for target '../../../../libretro/obj/libretro/emu.h.gch' failed
make[2]: *** [../../../../libretro/obj/libretro/emu.h.gch] Error 1
Makefile:70: recipe for target 'precompile' failed
make[1]: *** [precompile] Error 2
make[1]: Leaving directory '/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm'
Makefile:70: recipe for target 'precompile' failed
make[1]: *** [precompile] Error 2
make[1]: Leaving directory '/home/buildbot/buildbot/android/libretro-mame/build/projects/retro/mame/gmake-android-arm'
makefile:1093: recipe for target 'android-arm' failed
make: *** [android-arm] Error 2
makefile:1093: recipe for target 'android-arm' failed
make: *** [android-arm] Error 2
COPY CMD: cp -v mame_libretro_android.so /home/buildbot/buildbot/android/dist/android/armeabi-v7a/mame_libretro_android.so
cp: cannot stat 'mame_libretro_android.so': No such file or directory

**Comment by fr500** [comment]
Ok, changed the build line to the one you mentioned
Think it went further http://hastebin.com/oqiwuvigor

**Comment by r-type** [comment]
that is odd! it compile fine for me , i've just rebuild a tiny using the same cmdline as you (except for SUBTRAGET=tiny)

http://hastebin.com/uxijewiqiy.swift

BTW also i don't have the error msg you have at  the beginning
make: *** No rule to make target '"android-arm"', needed by 'all'.  Stop.
did you have some pb with quote or double quote ?

**Comment by fr500** [comment]
Doesn't seem like it...
Do I have to run make inside a particular dir? maybe I'm building with the wrong makefile

**Comment by r-type** [comment]
i just run make in the main 'mame' directory. 
could you try to remove your "" in cores-android-armv7-ndk-mame ?

 gcc="android-arm" OS="linux" TARGETOS="android-arm"

no sure it does anything but at this point ...

**Comment by r-type** [comment]
last resort can you also try just using make -f Makefile.libretro platform=android

**Comment by fr500** [comment]
So weird... now it prints this with only the quotes removed...
http://hastebin.com/otegonedol

**Comment by r-type** [comment]
yes weird...

seems you are now on gcc4.8 (not like before in 6.2)
 GCC 4.8 detected

After it fail here
Linking m68kmake...
make[1]: g++: Command not found
make[1]: *** [m68kmake] Error 127

strange.

**Comment by fr500** [comment]
I'll setup the environment manually and try to build manually tomorrow
Once that works I guess I can make it work on the buildbot

**Comment by r-type** [comment]
ok let me know if you get in trouble.

**Comment by fr500** [comment]
make platform=android
GCC 6.2.0 detected
fatal: No names found, cannot describe anything.
lstrlib.c
lvm.c
os_ticks.c
os_uuid.c
premake.c
premake_main.c
scripts.c
string_endswith.c
string_hash.c
Creating ../../bin/linux
Linking genie
Converting translation language/Korean/strings.po...
Converting translation language/English/strings.po...
Converting translation language/Hindi/strings.po...
Converting translation language/Russian/strings.po...
Converting translation language/Hebrew/strings.po...
Converting translation language/Burmese/strings.po...

No idea why that happens, maybe it doesn't like something about my environment variables...

**Comment by r-type** [comment]
yes,  above is because you are using platform=android with makefile , and not Makefile.libretro.
the short way is 
make -f Makefile.libretro platform=android 
(should works if you export before  ANDROID_NDK_LLVM ANDROID_NDK_ARM ANDROID_NDK_ROOT).

or the long way using makefile.

export ANDROID_NDK_LLVM="/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64" 
export ANDROID_NDK_ARM="/opt/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64" 
export ANDROID_NDK_ROOT="/opt/ndk"

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 NOASM="1" gcc="android-arm" OS="linux" TARGETOS="android-arm" CONFIG=libretro NO_USE_MIDI="1" TARGET=mame -j4

**Comment by r-type** [comment]
the actual error in buildbot for android
```
/home/buildbot/tools/android/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64//bin/clang++    -MMD -MP -MP -D__LIBRETRO__ -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../3rdparty/bgfx/3rdparty/khronos -I/home/buildbot/tools/android/android-ndk-r13b//sources/cxx-stl/llvm-libc++/libcxx/include -I/home/buildbot/tools/android/android-ndk-r13b//sources/android/support/include -I/home/buildbot/tools/android/android-ndk-r13b//sources/android/native_app_glue -I/home/buildbot/tools/android/android-ndk-r13b//platforms/android-21/arch-arm/usr/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util   -O2 -fPIC -pipe -Wno-deprecated-declarations -O3 -fno-strict-aliasing -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-cast-align -Wno-tautological-compare -Wno-unused-value -Wno-constant-logical-operand -Wno-missing-braces -fdiagnostics-show-note-include-stack -Wno-unknown-warning-option -Wno-extern-c-compat -Wno-unknown-attributes -Wno-ignored-qualifiers -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-integrated-as -Wunused-value -Wno-macro-redefined -gcc-toolchain /home/buildbot/tools/android/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/ -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wno-undef -Wno-typedef-redefinition -x c++ -std=c++14 -Woverloaded-virtual -Wno-extern-c-compat -Wno-tautological-constant-out-of-range-compare -Wno-tautological-pointer-compare -x c++-header -D__LIBRETRO__ -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DMAME_NOASM -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -I../../../../../3rdparty/bgfx/3rdparty/khronos -I/home/buildbot/tools/android/android-ndk-r13b//sources/cxx-stl/llvm-libc++/libcxx/include -I/home/buildbot/tools/android/android-ndk-r13b//sources/android/support/include -I/home/buildbot/tools/android/android-ndk-r13b//sources/android/native_app_glue -I/home/buildbot/tools/android/android-ndk-r13b//platforms/android-21/arch-arm/usr/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/lib/util  -o "../../../../libretro/obj/libretro/emu.h.gch" -c "../../../../../src/emu/emu.h"
../../../../../src/emu/emu.h:21:10: fatal error: 'list' file not found
#include <list>
         ^
../../../../../src/emu/emu.h:21:10: fatal error: 'list' file not found
#include <list>
         ^
1 error generated.
1 error generated.
```
it miss #include <list> , mainly because in r13 or above include path change for stl

https://gitlab.kitware.com/cmake/cmake/commit/0c3a04777cc5fa8bc43b57b789e72630781ef56a?view=inline

before r13 correct include is  ${ANDROID_NDK}/sources/cxx-stl/llvm-libc++/libcxx/include
but for r13 and above this is ${ANDROID_NDK}/sources/cxx-stl/llvm-libc++/include"

and in mame scripts/toolchain.lua line 838 we have

```
	configuration { "android-*" }
		objdir (_buildDir .. "android/obj/" .. _OPTIONS["PLATFORM"])
		includedirs {
			MAME_DIR .. "3rdparty/bgfx/3rdparty/khronos",
			"$(ANDROID_NDK_ROOT)/sources/cxx-stl/llvm-libc++/libcxx/include",
			"$(ANDROID_NDK_ROOT)/sources/android/support/include",
			"$(ANDROID_NDK_ROOT)/sources/android/native_app_glue",
		}
```
we could add  "$(ANDROID_NDK_ROOT)/sources/cxx-stl/llvm-libc++/include"
to the includedirs to solve this one.

**Comment by fr500** [comment]
Sorry @r-type I haven't had too much time on the weekend, family matters.

**Comment by r-type** [comment]
OK no problem 
BTW I tried with r13b and the include of above , it failed at final link.
So seem ndk13 not supported for now in mame .
we should stay and build with ndk <13.

**Comment by r-type** [comment]
I finally got r13b link successfully. I ll push a commit later.

BTW not sure if it works on device  because new Retroarch for android force automatically tu use either mame2014 core or mame 0.174 core ;(  .
I can't simply load my test core as core auto-detect don't give me the choice to use it.

@twinaphex  @fr500 is there any way to disabled auto detect core feature ?

**Comment by r-type** [comment]
@fr500 i thinks you don't have to change anything else for this core , after my commit we will see if it build fine with buildbot.

**Comment by r-type** [comment]
nice it seem that mame build successfully for android now , so we can close this one.

on side note I can't find a build log for mame windows on buildbot.

**Comment by r-type** [comment]
@fr500  any news about the windows build and the windows log ?
