### ISSUE TITLE
Failed to open libretro core with latest GlupeN64

### ISSUE THREAD

**Issue by diegoviola** [libretro/libretro-super#378]
As reported in this bug report:

https://github.com/libretro/RetroArch/issues/4179

The GlupeN64 build in the buildbot is broken for Linux (x86_64).

**Steps to reproduce:**

Load core -> Download core -> glupen64_libretro.so.zip
Load core -> glupen64_libretro.so
Load content -> Select File -> rom file
Should result in "Failed to open libretro core"

**System:**

Arch Linux (x86_64)
RetroArch git 3600e29

If I build glupen64 myself, it works fine.

**Expected results:**

Game works fine with the core.

**Comment by loganmc10** [comment]
I doesn't work for me with Ubuntu 16.10 either, this is the message I get:

```
Error(s): /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found
```

**Comment by ToppestOfDogs** [comment]
It doesn't work in Windows 10 64bit either. No error, it just boots back to retroarch.

**Comment by loganmc10** [comment]
@ToppestOfDogs can you try the version here:

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by ToppestOfDogs** [comment]
I've tried it, same issue.
Windows 10 64bit, GTX 1060, i5 4690K by the way.

**Comment by loganmc10** [comment]
Can you provide any log file? I'm not sure exactly how you'd do it on Windows but there is a way to get the RetroArch log output to see what is going on.

**Comment by ToppestOfDogs** [comment]
I don't know how to get a log. Everyone says to use --verbose but that doesn't do anything different. There's nothing in the command window.

**Comment by loganmc10** [comment]
Ya that is a RetroArch thing, it can't automatically figure out the proper video driver

**Comment by diegoviola** [comment]
This is still an issue for me as well.

I tried it with a recent build of RA (git 4c611e42c6cd6b136b4405d689749c2d875ada60) and glupen64 nightly build from the buildbot and the problem is still there.

**Comment by diegoviola** [comment]
Any solution for this? It's still an issue for me with the latest version of mupen64plus.

**Comment by diegoviola** [comment]
`pacman -Syu libpng12` fixed it for me with mupen64plus.

**Comment by Matthew98405** [comment]
Damn, wish I read that a month ago, with libpng12 installed, I can now use mupen64plus, as well. `libpng12` should be a dependency for retroarch and/or libretro-mupen64plus
