### ISSUE TITLE
RetroArch_debug.apk

### ISSUE THREAD

**Issue by loganmc10** [libretro/libretro-super#395]
I seem to recall that the buildbot used to produce a RetroArch_debug.apk

Is it possible to pick that up again? I am trying to use the Tegra Graphics Debugger with RetroArch and it wants a debuggable APK

**Comment by fr500** [comment]
It wasn't really a debuggable apk, I think we have to build differently for that (with ant debug instead) and it didn't include gdbserver.
If someone can give me the steps I can do it.

**Comment by loganmc10** [comment]
I believe it is as simple as using ```ant debug``` instead of ```ant release```

**Comment by fr500** [comment]
The build wouldn't allow moving back and forth to between regular and these builds. The signature would be different. Is that a problem?

**Comment by loganmc10** [comment]
No I would uninstall and reinstall the APK, I wouldn't expect you to be able to update a production APK with a debug build (I've never actually tried it, I just assumed it wouldn't work/work well)

**Comment by fr500** [comment]
what would be nice is being able to change the package name (so both can co-exist) but I dunno if that's just a matter of changing the manifest or the java stuff.

Anyway I'll try to get that debug stuff working later today.

**Comment by loganmc10** [comment]
Just a "bump", if there is anything I can do for this let me know, I'm not sure what all needs to change for the buildbot to accomplish this.

This will allow me to do a bit of performance profiling for glupen64 on the shield tablet and hopefully eek out some more performance from it.
