### ISSUE TITLE
All platforms not getting nightlys

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/libretro-super#419]
Mac_32bit is a year out of date.
Mac_64bit,IOS,IOS9,Linux x86_32bit,Linux armhf have not got a nightly for 3 weeks.
Linux_armel has no nightlys at all.

Android(all) and Linux x86_64 are the only ones working properly.

**Comment by twinaphex** [comment]
@hunterk @hizzlekizzle You want to respond here regarding the status of the buildbot?

**Comment by fr500** [comment]
@meepingsnesroms uh.... windows is fine:

**Comment by meepingsnesroms** [comment]
Sorry about that.
