### ISSUE TITLE
Add mame2016 recipes 

### ISSUE THREAD

**Issue by r-type** [libretro/libretro-super#435]
@twinaphex @fr500  could you try to add recipes for mame2016 core ?

android32arm should build fine with add in cores-android-armv7-ndk-mame

```
mame2016  libretro-mame2016 https://github.com/libretro/mame2016-libretro PROJECT YES GENERIC makefile . OSD=retro RETRO=1 NOWERROR=1 NOASM=1 gcc=android-arm gcc_version=4.9 TARGETOS=android-arm CONFIG=libretro NO_USE_MIDI=1 OS=linux VERBOSE=1 verbose=1 TARGET=mame 
```

win64 should build fine with adding in cores-windows-x64_seh-generic

```
mame2016  libretro-mame2016 https://github.com/libretro/mame2016-libretro PROJECT YES GENERIC Makefile.libretro . PTR64=1 
```
linux64 should build fine with adding in cores-linux-x64-generic

```
mame2016  libretro-mame2016 https://github.com/libretro/mame2016-libretro PROJECT YES GENERIC Makefile.libretro . 
```

**Comment by r-type** [comment]
info file could be 
```
display_name = "Arcade (MAME 2016)"
authors = "MAMEdev"
supported_extensions = "zip|chd|7z|cmd"
corename = "MAME 2016 (0.174)"
manufacturer = "Various"
categories = "Emulator"
systemname = "Arcade (various)"
database = "MAME"
license = "MAME"
permissions = ""
display_version = "0.174"
supports_no_game = "false"
notes = "[1] MAME 2016 (0.174) supports MAME save states.|[2] MAME 2016 (0.174) supports extracted MAME cheats.|[3] The BIOS files must be inside the ROM directory.|[4] The same directory with CHD files inside must be inside the ROM directory.|[5] If desired, the ARTWORK, CHEATS, and SAMPLES directories can be|[^] inside the 'SYSTEMDIR\mame' directory.|[6] When saving, the following directories will be created in the 'SAVEDIR\mame'|[^] directory: STATES, NVRAM, INPUT, SNAPS, CFG, MEMCARD, and DIFF."
```

BTW for mame_libretro.info 
supported_extensions = "zip|chd|7z|cmd"

**Comment by twinaphex** [comment]
Added -

https://github.com/libretro/libretro-super/commit/c5655f92772ab25ef65bb50096c8e2af8ac4fb52

**Comment by r-type** [comment]
Looking at the log ,
Android build is fine (works) kitkat and lollipop.
Linux failed to build but it's my fault I'll will push a fix quickly

**Comment by r-type** [comment]
fix pushed , linux64 should build.
BTW there no log for win64 build so can say what is going on the mame2016  core.
also  mame2016 support cmd files , supported_extensions = "zip|chd|7z|cmd"

**Comment by r-type** [comment]
Ok all 3 are fine now and available on buildbot.
just missing the cmd for mame2016_libretro.info but it's a little issue.
thanks for added these core  @twinaphex 
I'll close the issue then.

**Comment by r-type** [comment]
I reopen because it seem the rebase break some things a least for linux.
the last linux log show 
```CLEANUP CMD:  make -f Makefile.libretro platform=unix_ -j6 clean
make REGENIE=1 VERBOSE=1 NOWERROR=1 OSD="retro" PYTHON_EXECUTABLE=python2 CONFIG=libretro  LIBRETRO_OS="unix" ARCH="" LIBRETRO_CPU="x86_64"  clean
make[1]: Entering directory '/home/buildbot/buildbot/linux_x86_64/libretro-mame2016'
makefile:18: *** missing separator.  Stop.
make[1]: Leaving directory '/home/buildbot/buildbot/linux_x86_64/libretro-mame2016'
Makefile.libretro:198: recipe for target 'clean' failed
make: *** [clean] Error 2
--------------------------------------------------
BUILD CMD:  make -f Makefile.libretro platform=unix -j6
make REGENIE=1 VERBOSE=1 NOWERROR=1 OSD="retro" PYTHON_EXECUTABLE=python2 CONFIG=libretro  LIBRETRO_OS="unix" ARCH="" LIBRETRO_CPU="x86_64" 
make[1]: Entering directory '/home/buildbot/buildbot/linux_x86_64/libretro-mame2016'
makefile:18: *** missing separator.  Stop.
make[1]: Leaving directory '/home/buildbot/buildbot/linux_x86_64/libretro-mame2016'
Makefile.libretro:195: recipe for target 'build' failed
make: *** [build] Error 2
BUILD CMD /home/buildbot/buildbot/linux_x86_64/retrolink.sh mame2016_libretro.so
readelf: Error: 'mame2016_libretro.so': No such file
readelf: Error: 'mame2016_libretro.so': No such file
COPY CMD: cp -v mame2016_libretro.so /home/buildbot/buildbot/linux_x86_64/dist/unix//mame2016_libretro.so
cp: cannot stat 'mame2016_libretro.so': No such file or directory

```
i don't understand why it break at makefile 18 , I have built it fine on linux on my hand.

**Comment by r-type** [comment]
same happen to android buildbot build break at line 18

**Comment by r-type** [comment]
@fr500 any clue about this ?  

it work for windows , but linux and android buildbot failed with mysterious error at line .
but they compile fine by hand (also on nightly ppa ) with 
```
 make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 ANDROID_NDK_ARM="/opt/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64" NOASM="1" ANDROID_NDK_ROOT="/opt/ndk" gcc="android-arm" OS="linux" TARGETOS="android-arm" CONFIG=libretro NO_USE_MIDI="1"  OVERRIDE_CC=/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64/bin/clang OVERRIDE_CXX=/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64/bin/clang++ TARGET=mame -j4

make OSD="retro" verbose=1 RETRO=1 NOWERROR=1 OS="linux" TARGETOS="windows" CONFIG="libretro" NO_USE_MIDI="1" PTR64=1 TARGET=mame GCC="mingw64-gcc" -j10

make -f Makefile.libretro TARGET=mame  -j10
```

**Comment by r-type** [comment]
Any news about the issue ?
that strange as the same command used in buildbot using in a terminal
with make works fine and compile the core for both linux and android , 
nightly ppa build fine too for arm,i386 and x64 , 
but buildbot failed with an error at makefile 18 !!!

**Comment by fr500** [comment]
Oh I hadn't seen this...
But really no idea....

From the error you post it's running this: make -f Makefile.libretro platform=unix -j6
that's not the correct command right?

**Comment by fr500** [comment]
Can't check right now, but make sure the recipes have a trailing space!
Every recipe line must have a trailing space

**Comment by r-type** [comment]
ok i will check

**Comment by r-type** [comment]
for mame2016 linux yes it's missing a trailing space
```
mame2016  libretro-mame2016 https://github.com/libretro/mame2016-libretro PROJECT YES GENERIC Makefile.libretro .
```

**Comment by r-type** [comment]
I don't understand the problem. i see bad char at line 18.

**Comment by fr500** [comment]
I think it built now
AlcaRobot> mame2016: [status: done]
[recipes/android/cores-android-armv7-ndk-old-mame]

**Comment by r-type** [comment]
yes it works now , 
what  did you do to solve the problem?

**Comment by fr500** [comment]
Well, changing the recipe doesn't really trigger a rebuild, so I removed
the mame clones on the buildbot...
Also did you force push to any repo? if you did then that may have been the
problem the buildbot doesn't know how to resolve that

**Comment by r-type** [comment]
Yes force push because I rebase it few day after 0.174 release to solve problem for some games .
And reapply patchs after.
That sould explain why the buidbot was not able to build it.
Now it works fine. And game like wbml who was crashing are fine now. Osd font too.

**Comment by r-type** [comment]
@fr500 seem mame2016 disappear from nightly and there are no change in source code.
any clue about this ?
