### ISSUE TITLE
Move Android recipes for mame2016/2014 from ndk13 to old ndk10

### ISSUE THREAD

**Issue by r-type** [libretro/libretro-super#436]
Seem there is some issues with ndk13 and mame2016/2014 android core.
For example it segfault if you enter dipswitch menu and it doesn't happen with other arch like lin64/win64

But if you build both core with ndk10 (I've tested ith ndk10d) , it doesn't segfault in dipswitch menu.

I don't know if you always have an old ndk setup with buildbot, but if it's the case could you look at to add recipe for mame2014/2016 using ndk10 instead of ndk13.

I built the both core using this config for ndk10d

```
export ANDROID_NDK_ARM=/opt/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
export ANDROID_NDK_ROOT=/opt/ndk
export ANDROID_NDK_LLVM=/opt/ndk/toolchains/llvm-3.5/prebuilt/linux-x86_64
```
and makefile arg for mame2014
```
make -f Makefile platform=android -j10 TARGET=mame
```
and makefile arg for mame2016
```
make  OSD=retro RETRO=1 NOWERROR=1 NOASM=1 gcc=android-arm gcc_version=4.9 TARGETOS=android-arm CONFIG=libretro NO_USE_MIDI=1 OS=linux VERBOSE=1 verbose=1 TARGET=mame -j10
```
@fr500 @twinaphex  if you can look at this ,i would be great!

**Comment by r-type** [comment]
we can add 2 mame recipes for old ndk like this

cores-android-armv7-ndk-old-mame.conf
```
PATH home/buildbot/tools/android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/
ANDROID_NDK_ARM /home/buildbot/tools/android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/
ANDROID_NDK_ROOT /home/buildbot/tools/android/android-ndk-r10e/
ANDROID_NDK_LLVM /home/buildbot/tools/android/android-ndk-r10e/toolchains/llvm-3.5/prebuilt/linux-x86_64/
PLATFORM android
platform android
LIBSUFFIX _android
MAKE make
DIST armeabi-v7a
CORE_JOB YES
```
cores-android-armv7-ndk-old-mame
```
mame2014 libretro-mame2014 https://github.com/libretro/mame2014-libretro.git PROJECT YES GENERIC Makefile . TARGET=mame 
mess2014 libretro-mame2014 https://github.com/libretro/mame2014-libretro.git PROJECT YES GENERIC Makefile . TARGET=mess 
ume2014 libretro-mame2014 https://github.com/libretro/mame2014-libretro.git PROJECT YES GENERIC Makefile . TARGET=ume 
mame2016 libretro-mame2016 https://github.com/libretro/mame2016-libretro PROJECT YES GENERIC makefile . OSD=retro RETRO=1 NOWERROR=1 NOASM=1 gcc=android-arm gcc_version=4.9 TARGETOS=android-arm CONFIG=libretro NO_USE_MIDI=1 OS=linux VERBOSE=1 verbose=1 TARGET=mame
```

After I'm not sure how libretro-super works and launch this recipes

**Comment by fr500** [comment]
if the tools are there and you add the files it should "just work"
let me check what's available

**Comment by fr500** [comment]
```
drwxrwxr-x 10 buildbot buildbot 4096 Apr  7  2015 android-ndk-r10e
drwxr-xr-x  8 buildbot buildbot 4096 Mar 30  2016 android-ndk-r11c
drwxr-xr-x 10 buildbot buildbot 4096 Oct 12 09:23 android-ndk-r13b
drwxrwxr-x 10 buildbot buildbot 4096 Oct 30 23:50 android-sdk-linux
drwxrwxr-x 12 buildbot buildbot 4096 Aug  5  2015 android-sdk-linux-old
drwxrwxr-x  9 buildbot buildbot 4096 Feb  8  2016 standalone-r10e-api21-arm
drwxrwxr-x 10 buildbot buildbot 4096 Feb  8  2016 standalone-r10e-api21-x86
drwxrwxr-x 11 buildbot buildbot 4096 Dec  1 16:26 standalone-r13b-api18-arm
drwxrwxr-x 11 buildbot buildbot 4096 Nov  4 01:02 standalone-r13b-api23-arm

```

**Comment by fr500** [comment]
feel free to add recipe files, I'll make libretro-buildbot run them

**Comment by r-type** [comment]
Thanks for looking at, I'll PR the recipes files then .

**Comment by r-type** [comment]
https://github.com/libretro/libretro-super/pull/437

**Comment by r-type** [comment]
@fr500 the recipes files don't seem to be run by buildbot
As mame 2014/2016 cores and builbot log for them just disappear from updater and from buildbot.
Can you take a look to activate them ?

**Comment by fr500** [comment]
Done, I renamed the dirs to make sure they run cleanly

**Comment by r-type** [comment]
Ok that fine now for mame2016.

BTW we have a little error for mame2014 because it create a mame2014_libretro.so
and script want a mame2014_libretro_android.so.

````
Linking mame2014_libretro.so
cp: cannot stat 'mame2014_libretro_android.so': No such file or directory
````
i will look at src to change target for android

**Comment by r-type** [comment]
All the 4 cores are now  built for android .
thanks ! I will close issue now.
