### ISSUE TITLE
[Feature Request] Support for cmd files for mame2016 and mess2014

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-super#450]
Similar to this [commit](https://github.com/libretro/libretro-super/commit/842bceef0f2c8ef29ffe3391e26a52fdec4a28b8)

**Comment by meepingsnesroms** [comment]
This belongs in those core repos or libretro-meta this repo is for issues with the buildbot or shell scripts.

**Comment by zach-morris** [comment]
OK.  I can move it to meta then I suppose.  I put it here since the commit referenced was made in this repo.

FWIW, [mame2016](https://github.com/libretro/mame2016-libretro/blob/fdaf14a6ec4f2df9344fd577d49580c6ed45fbbb/src/osd/retro/libretro.cpp#L391) and [mess2014](https://github.com/libretro/mame2014-libretro/commit/d58f0ad136fecaa1712fd8bdcf3670ef100648ad) already appear to support the cmd file type, but the info file does not include cmd as a supported extension.
