### ISSUE TITLE
Feature request - Have Make use all CPU cores when compiling

### ISSUE THREAD

**Issue by gjannece** [libretro/libretro-super#453]
I was compiling on Nvidia Jet TX1 system (arm arch) and noticed that it was using only 1 cpu core out of 4 to compile. I believe this is a config issue that can be solved with the -j arg. I think this is something that could be handled in the config script and used everywhere else.

**Comment by orbea** [comment]
This is something you should fix on your end. Edit /etc/profile or somewhere and add this.
```
export MAKEFLAGS='-j 2'
```
Substitute 2 for how many cores your cpu has.

**Comment by orbea** [comment]
You should also be able to do.
```
JOBS=2 ./libretro-build.sh
```

**Comment by gouchi** [comment]
Please close this issue.
