### ISSUE TITLE
Gpsp core fails to load on Android ('has text relocations')

### ISSUE THREAD

**Issue by wgrthoen** [libretro/libretro-super#466]
After the Retroarch upgrade to 1.6.0, the Gpsp core fails to load.

The relevant error in the logcat is as follows: 

```
06-09 11:54:50.620  9369  9385 E RetroArch: Failed to open libretro core: "/data/data/com.retroarch/cores/gpsp_libretro_android.so"
06-09 11:54:50.620  9369  9385 E RetroArch: Error(s): dlopen failed: /data/data/com.retroarch/cores/gpsp_libretro_android.so: has text relocations
```

Thinking the core and info file were outdated I manually pushed the core from: https://bot.libretro.com/nightly/android/latest/armeabi/ to my phone. It sadly gives me the exact same error: 

```
06-09 12:05:45.701  9369  9385 E RetroArch: Failed to open libretro core: "/data/data/com.retroarch/cores/gpsp_libretro_android.so"
06-09 12:05:45.702  9369  9385 E RetroArch: Error(s): dlopen failed: /data/data/com.retroarch/cores/gpsp_libretro_android.so: has text relocations
```

If I look up whats this means I come up with this: https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23. Which in short tells us that text relocations in .so files will not be allowed for API level 23 and above.

 I Assume the API level was pushed to 23 with the RetroArch 1.6.0 release.

The reason I would still like to use the Gpsp core is that it gives me significantly better performance and battery life in comparison to the Mgba core on my Android phone. 

Now I am not sure what the best way would be to go about and solving this, if possible at all. The possibilities I see now are:

1. If the assembly is part of Gpsp itself it might be hard to rewrite this to conform to the needed PIC standard: https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide#How_to_write_PIC_.28in_theory.29. Re-
writing assembly is beyond my programmaing skills :(
2. Bring down the API level of the RetroArch Android build to 22 to prevent android from denying the dload() of the .so file. This doesn't seem like a real long term solution.
3. There have also been some old issues mentioned 'around the interwebs' with the NDK generating .so files with TEXTREL sections. If the android builds are done with one of these older versions simply upgrading the build NDK version could possibly solve it.
4. Downgrade RetroArch on my mobile to 1.50 and use that for now, but that is not a sustainable solution and wouldn't help other users.
5. Maybe other options/info I missed?

If I missed anything or could provide more feedback to help this issue along please let me know.

**Comment by twinaphex** [comment]
Hi there @notaz,

seems gpsp is the latest to fall victim to Google's ban on text relocations now -

You can find the repo here.

https://github.com/libretro/gpsp

**Comment by orbea** [comment]
@wgrthoen Is this still a problem? If so can you report it in the correct repo linked above?

https://github.com/libretro/libretro-super/issues/466

**Comment by orbea** [comment]
@wgrthoen Is this still a problem? If so can you report it in the correct repo linked above?

https://github.com/libretro/gpsp

**Comment by wgrthoen** [comment]
Yes as of version 1.6.9. Created the issue there: https://github.com/libretro/gpsp/issues/41

**Comment by orbea** [comment]
@wgrthoen Thanks! Mind closing this issue so that all discussion can happen on the correct repo? Unfortunately I don't know how to solve it, but hopefully someone else will actually see the issue now? :)
