### ISSUE TITLE
Add Nintendo 3DS Homebrew Sample

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-super#474]
Add [some 3DS homebrew](https://wiki.gbatemp.net/wiki/List_of_3DS_homebrew) to the Content Downloader:
https://buildbot.libretro.com/assets/cores/

[3DS Pong](https://github.com/shinyquagsire23/3DS-Pong) may be a good candidate.

**Comment by hizzlekizzle** [comment]
Are any of them permissively licensed? I see Turtle: Invaders is CC-4.0 noncomm-attribution, which is probably fine but we don't really have any way of providing the attribution component. I'd really like to get [this 3DS Hardware Test](https://gbatemp.net/threads/release-3ds-hardware-test.438267/) on there (I try to provide hardware/controller tests for as many cores as possible), if we can get someone with an account there to request permission.

**Comment by gingerbeardman** [comment]
I've asked https://gbatemp.net/threads/release-3ds-hardware-test.438267/page-2#post-7418342

**Comment by RobLoach** [comment]
When running the 3DS Hardware test, I get failed to find index.lua. HAve you been able to run it?

**Comment by RobLoach** [comment]
Created an issue on https://github.com/TricksterGuy/bottomless-block-barrage ... Looks like a great Tetris Attack clone under the GPL.

**Comment by gingerbeardman** [comment]
I see you got the go-ahead? https://github.com/TricksterGuy/bottomless-block-barrage/issues/16

**Comment by RobLoach** [comment]
Great, added it in. Thanks for the ping.
