### ISSUE TITLE
updated RDB databases not appearing in online updater

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#478]
This started as [an issue in the libretro-database repo](https://github.com/libretro/libretro-database/issues/472), but after hearing from @RobLoach there it seems like the buildbot is involved and is therefore a libretro-super issue.

Here's what I do:

1. Download the latest RA nightly
2. I start RA then select Update Core Info Files
3. I then select Update Databases

After both downloads/extractions complete, the result is an info folder which has all of the new .info files, but the database folder does not have the new RDB files.

For example, here is one of the new RDBs that is not being distributed by the online updater: https://github.com/libretro/libretro-database/blob/master/rdb/MAME%200.78.rdb

**Comment by RobLoach** [comment]
You can see the versioned MAME RDBs are not being uploaded to buildbot:
https://buildbot.libretro.com/assets/frontend/bundle/database/rdb/

Where are the buildbot scripts for this?

**Comment by RobLoach** [comment]
Done! Thanks Radius :+1:
