### ISSUE TITLE
the dot / period character (.) is not properly escaped when generating playlists

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#480]
@RobLoach I am not sure whether this is a libretro-super issue or a libretro-database issue. The good news is that I can now scan MAME 0.78 ROMsets via standard Windows RetroArch after updating databases from the online updater.

The other news is that the playlist which appears is named `MAME 0.lpl` which will need to be renamed to `MAME.lpl` in order to show thumbnails from libretro-database. If it works this way in perpetuity, this is so much better than the previous situation that I think it will be fine.

On the other hand I thought the playlist name was a little odd (maybe `MAME 0.78.lpl` would be more descriptive) so in case it isn't meant to do this I wanted to check with you.

**Comment by RobLoach** [comment]
In the Playlists section?

![screenshot at 2017-07-06 16-45-59](https://user-images.githubusercontent.com/25086/27932137-a163cdc2-626a-11e7-8e61-551c8187412b.png)

**Comment by markwkidd** [comment]
Here's what I see:
![screenshot 2017-07-06 16 46 54](https://user-images.githubusercontent.com/19554678/27932221-f9c0e608-626a-11e7-87e9-4964203934d6.png)
![screenshot 2017-07-06 16 47 17](https://user-images.githubusercontent.com/19554678/27932224-fbc07928-626a-11e7-8e65-d19946998740.png)

**Comment by markwkidd** [comment]
The playlist itself looks fine:

![screenshot 2017-07-06 16 49 30](https://user-images.githubusercontent.com/19554678/27932279-25e22abc-626b-11e7-92e6-15006e6b2d93.png)

**Comment by markwkidd** [comment]
@RobLoach this seems like it must be an issue with the code that creates playlist files not handling the dot (".") character correctly and truncating the filename at that point.

If I change the RDB file to be MAME 078.rdb and I change the corresponding name in the .info file, the playlist generates with the full name of the database as expected.

I'm going to open a bug in the RetroArch repo.

**Comment by markwkidd** [comment]
New Issue in libretro/RetroArch: https://github.com/libretro/RetroArch/issues/5182
