### ISSUE TITLE
BuildBot: Dependencies

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-super#485]
Could we install additional development packages on the buildbot? [chaigame_unix.log](https://buildbot.libretro.com/log/2017-07-15_chaigame_unix.log) reports the following:

```
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -lmikmod
/usr/bin/ld: cannot find -lvorbisfile
/usr/bin/ld: cannot find -logg
```

The packages required include:
```
libjpeg-dev
libpng12-dev
libfreetype6-dev
libmikmod-dev
libvorbis-dev
libogg-dev
```

Or should I compile them locally?

**Comment by twinaphex** [comment]
No, make sure your cores compile without any dynamic library dependencies. This is a clear line in the sand as far as libretro cores go, and for very good reason.
