### ISSUE TITLE
Add some vice info/recipes 

### ISSUE THREAD

**Issue by r-type** [libretro/libretro-super#495]
I made some additional makefile for vic20 and plus4 core.
all we need now is to add the recipes and the info fles.

recipe could be like 
```
vice_xvic libretro-vice_xvic https://github.com/libretro/vice-libretro.git master PROJECT YES GENERIC Makefile . EMUTYPE=xvic
vice_xplus4 libretro-vice_xplus4 https://github.com/libretro/vice-libretro.git master PROJECT YES GENERIC Makefile . EMUTYPE=xplus4
```
and info file 

vice_xplus4_libretro.info
```
display_name = "Commodore PLUS4 (VICE)"
authors = "VICE Core Team Members"
supported_extensions = "d64|d71|d80|d81|d82|g64||g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z"
corename = "VICE"
manufacturer = "Commodore"
categories = "Emulator"
systemname = "PLUS4"
database = "Commodore - PLUS4"
license = "GPLv2"
permissions = ""
display_version = "v3.0"
supports_no_game = "false"
```
vice_xvic_libretro.info

```
display_name = "Commodore VIC20 (VICE)"
authors = "VICE Core Team Members"
supported_extensions = "d64|d71|d80|d81|d82|g64||g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z"
corename = "VICE"
manufacturer = "Commodore"
categories = "Emulator"
systemname = "VIC20"
database = "Commodore - VIC20"
license = "GPLv2"
permissions = ""
display_version = "v3.0"
supports_no_game = "false"
```
@twinaphex  could you look at and see if someone can add info and recipes for linux/win/osx/wiiu
/android ?

**Comment by r-type** [comment]
@twinaphex 
done basic job here https://github.com/libretro/libretro-super/pull/508
should be fine , but just in case can someone just review it before merging.

**Comment by twinaphex** [comment]
The only issue I get so far is this while running libretro-fetch -

=== vice_xvic
libretro_fetch:No URL set to fetch vice_xvic via git.

**Comment by r-type** [comment]
yeah i see my erro i will PR soon

**Comment by r-type** [comment]
did it solve the fetch ?

**Comment by twinaphex** [comment]
Yes it did. Thanks.

**Comment by gouchi** [comment]
This issue should be closed because of [this PR](https://github.com/libretro/libretro-super/pull/508).
