### ISSUE TITLE
buildbot not building MAME 2016

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#535]
This issue began as a thread in the forums: https://forums.libretro.com/t/mame-2016/12238/

It seems that currently there is an issue with the MAME 2016 recipe preventing it from being built by the buildbot.

**Comment by estefan3112** [comment]
The latest successful MAME compile under MacOS has been on 14 November 2016. I guess that "MAME 2016" now runs under "MAME" (current).

The MacOS builds of libretro/mame seem to build properly:
https://github.com/libretro/mame

So is it a problem of libretro-super here?

**Comment by fr500** [comment]
Ok mystery solved, buildbot cleans up files from 2016 and 2017 automatically
Fixed :p
