### ISSUE TITLE
libretro-build.sh, some missing cores

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-super#609]
i have been using this script to batch compile and update cores i care about. some are missing like:

libretro_build_core px68k
libretro_build_core yabause
libretro_build_core mednafen_saturn
libretro_build_core atari800

any way we can add these cores(and probably others not in my list but also missing?)

**Comment by orbea** [comment]
What OS are you using?

**Comment by retro-wertz** [comment]
linux atm. i can add them fine, but what im suggesting is permanent addition of them into the script, but im not familiar enough with other platforms they support to properly categorize them in proper places.

**Comment by orbea** [comment]
I think `yabause` should build, is this wrong?

**Comment by retro-wertz** [comment]
ah ok yeah, yabause is there already.. so just probably the others then..

thanks

**Comment by sergiobenrocha2** [comment]
See #500

**Comment by retro-wertz** [comment]
closing this to continue issue to an already existing topic.
