### ISSUE TITLE
Android MAME 2016 build issues

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#628]
It seems that there are some more issues with the Android MAME 2016 core -- from what I understand it is being incorrectly deleted by the buildbot after compilation but that is not confirmed. I'm going to ask a few folks who are affected by the problem to post here, hopefully with more specifics.

**Comment by fr500** [comment]
It's no longer being deleted.

**Comment by markwkidd** [comment]
@fr500 thanks. I've been getting some private messages about this, I will try to make sure those users have checked the buildbot recently...

**Comment by orbea** [comment]
Can someone explain the current use case that is broken? I don't have an android build environment setup...

**Comment by markwkidd** [comment]
According to one forum user they are now seeing this core in the buildbot. I'm going to close the isue unless someone else steps up with more of a report.
