### ISSUE TITLE
Unable to compile Citra Libretro

### ISSUE THREAD

**Issue by hyarsan** [libretro/libretro-super#675]
I am not sure where to post this but... Citra Libretro won't compile for Windows! At least the build bot doesn't work for Windows! :( Citra Libretro for Windows is currently stuck on an old version.

**Comment by orbea** [comment]
Details? How is it failing?

**Comment by hyarsan** [comment]
Thank you for being the only one interested in fixing it I guess!

Do I really have to go through the mess of compiling it again? Anyways, I had tried what @j-selby said but it didn't work.
You can see the conversation on here: https://gbatemp.net/threads/3ds-emulator-citra-now-has-networking-support.488527/page-5#post-7762416

Hold on, I'll attempt to compile this again really quick.

**Comment by hyarsan** [comment]
CMake Error: Could not create named generator MSYS Makefiles

-_-

**Comment by orbea** [comment]
I'm sorry, but finding the relevant details in that forum thread is kind of hard, can you start over and give a full bug report? What commands are you running to initiate a build? What cmake version? A full build log could help too.

But first, can you make sure you have the latest commit for libretro-super? There was a similar issue reported for citra that should now be fixed.
https://github.com/libretro/libretro-super/issues/610
https://github.com/orbea/libretro-super/commit/bf44dd182ffd8a45a75cb3311f644830e1f1468d

**Comment by orbea** [comment]
I was given more details in irc, it seems I broke it again by mistake... Can you make sure the referenced PR fixes it for you?

**Comment by hyarsan** [comment]
I just downloaded it, it is version a0a4d69 which seems familiar to me? Or do I just need to wait a little until it is taken into effect?

**Comment by orbea** [comment]
I was hoping you could test it manually, as I do not know how to access the windows buildbot (If I even can?) I can't force a rebuild and as neither citra nor its recipe were updated it won't force a rebuild itself...

**Comment by hyarsan** [comment]
I guess it gets updated nightly, cya tomorrow! :P

**Comment by orbea** [comment]
I don't think it will build unless someone removes the repo from the buildbot, the citra recipe changes or citra gets new commits. Does citra get updated nightly?

**Comment by orbea** [comment]
fr500 removed the repo so it should clone and rebuild the next time the buildbot gets to it. You can watch #libretro-buildbots @ freenode if you want to see when this happens.
