### ISSUE TITLE
building the new FreeIntv Intellivision core

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#689]
Is it possible or premature to start incorporating recipes for the new FreeIntv libretro core into the buildbot? https://sourceforge.net/projects/freeintv/

Would that mean that the sourceforge repo would have to be cloned to a github repo as a first step?

**Comment by fr500** [comment]
I think you can import svn into git easily at least

**Comment by ofry** [comment]
by this link I not see any SVN repo. I see only 1 release with source code included. No more.

**Comment by markwkidd** [comment]
@bparker06 I will double check with recompile, but I don't think that FreeIntv has been using the SVN functionality of sourceforge. SF is being used just to distribute the source and precompiled binary for rpi. I'll post again once I can confirm.

**Comment by bparker06** [comment]
Ah, my mistake then. Yea I'm not seeing any repository.

**Comment by markwkidd** [comment]
I haven't worked hands on with SourceForge in ages so I wasn't sure myself. recompile confirms what you found that there is no SVN commit history, just this first public release.

**Comment by orbea** [comment]
It doesn't contain a makefile either...

**Comment by ofry** [comment]
https://github.com/markwkidd/FreeIntv/issues/1

**Comment by markwkidd** [comment]
Thanks @ofry I'm not terribly familiar with Makefiles, but I've taken a crack at adapting the mame2003 Makefile which I've worked with before. Here's how it looks now: https://github.com/markwkidd/FreeIntv/blob/master/Makefile

I can compile FreeIntv in Windows and Ubuntu with it, but the core is crashing when run. I assume we can move the Makefile discussion to your FreeInvt issue ticket but I though I should post here in case others are interested or more qualified than I for this step.

**Comment by markwkidd** [comment]
Hi folks, with a little help from the community, this core is now compiling via the Makefile and working fine in Windows 7 as far as I can tell.

Does this hopefully move us closer to buildbot integration?

**Comment by orbea** [comment]
Thanks. I made a PR to add FreeIntv to os, ios9, osx, linux-armhf, linux-x86, linux-x64, windows-x64_seh and windows-x86_dw2 recipes. This still leaves the various consoles and android which I think will require a jni makefile?

**Comment by orbea** [comment]
Seems to have built fine for everything so far, but someone else will have to test most of them.

**Comment by markwkidd** [comment]
@orbea thanks for helping with this! I'm going to take the liberty of closing this issue for now -- clearly the core is building via the buildbot. Woot!

I will also open a new issue focused on the JNI files for the missing platforms in the hopes of attracting someone with the relevant expertise.
