### ISSUE TITLE
[3DS] nightly builds broken (no cores at all) since 2018-01-11

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/libretro-super#694]
since yesterday 2018-01-11

no cores are in the nightly archives

Also, this should be easy to catch automatically?

**Comment by orbea** [comment]
@meepingsnesroms Mind explaining what happened here? I suspect this is the result of some recent changes, but I don't know the details.

**Comment by meepingsnesroms** [comment]
This is because I added battery level reporting to the 3ds port and it requires a new version of libctru, they are using one over a year old so it cant find a missing header "mcuhwc.h", when libctru is updated all cores will start working like before.

**Comment by gingerbeardman** [comment]
Thanks for the info. What’s holding the updated libctru?

**Comment by meepingsnesroms** [comment]
Opinions on how to update the toolchain, its up to date now and compiling again.

**Comment by orbea** [comment]
So what's the status on this issue? Is it fixed?

**Comment by gingerbeardman** [comment]
Yes, from yesterdays nightly we are good
