### ISSUE TITLE
MAME (current) still does not compile on MacOS

### ISSUE THREAD

**Issue by estefan3112** [libretro/libretro-super#736]
Latest MacOS and Xcode tells me the following on ./libretro-build.sh mame
(after a long, maybe successful compile):

2 warnings during Compiling generated/mame/mame/drivlist.cpp...

In file included from ../../../../../src/osd/libretro/retromain.cpp:24:
../../../../../src/osd/libretro/osdretro.h:26:6: warning: 'USE_XINPUT' is not defined, evaluates to 0 [-Wundef]
#if (USE_XINPUT)
     ^
../../../../../src/osd/libretro/retromain.cpp:80:6: warning: 'USE_XINPUT' is not defined, evaluates to 0 [-Wundef]
#if (USE_XINPUT)
     ^
2 warnings generated.

Then the errors during the linking process:

Linking mame_libretro.dylib...
Undefined symbols for architecture x86_64:
  "osd::dynamic_module::open(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&&)", referenced from:
      pcap_module::probe() in libosd_retro.a(pcap.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../../../../../mame_libretro.dylib] Error 1
make[2]: *** [mame] Error 2
make[1]: *** [macosx_x64_clang] Error 2
make: *** [build] Error 2
cp "mame_libretro.dylib" "/Users/xxxxxxxxxxxxxxxxx/Documents/RetroArch/libretro-super/dist/osx-x86_64/mame_libretro.dylib"
cp: mame_libretro.dylib: No such file or directory
1 core(s) failed:
   mame

Is there anything that can be done here to have a running current MAME core in Retroarch? Would be so great. Thanks and cheers!

**Comment by cold-brewed** [comment]
I believe this is a duplicate of issue [#63](https://github.com/libretro/mame/issues/63) in the libretro mame core. This should be addressed by [PR #94](https://github.com/libretro/mame/pull/94) in the same place.

**Comment by estefan3112** [comment]
Hi, many thanks for looking into this.
However, 'make -j5' ends up with an error 2 again.
Any special build instructions required?
Many thanks

> I believe this is a duplicate of issue [#63](https://github.com/libretro/mame/issues/63) in the libretro mame core. This should be addressed by [PR #94](https://github.com/libretro/mame/pull/94) in the same place.

**Comment by estefan3112** [comment]
The core now compiles under libretto-super. The MAME Core is now version 206. Many thanks.
