### ISSUE TITLE
Gearboy build platforms 

### ISSUE THREAD

**Issue by drhelius** [libretro/libretro-super#753]
Is it possible to build Gearboy on more platforms?

AFAIK it's being built for Windows and Linux only but the Makefile supports more platforms. 

Is there anything I can do to help with this?

**Comment by fr500** [comment]
Sure, I can try adding it to wiiu, ps3, osx
android needs a jni makefile those are a bit more difficult

**Comment by drhelius** [comment]
Let me know if I can be of any help

**Comment by fr500** [comment]
Added it to a few
PS3 failed, WiiU worked

http://p.0bl.net/171678

iOS failed http://p.0bl.net/171594

Still haven't made a jni makefile, I guess, I could add it for Wii/3DS/Vita/PSP if you think it would be fast enough for those.

**Comment by drhelius** [comment]
It runs smoothly on Raspberry Pi 2 and 3 for your reference, I don't know how is the performance of those consoles.

I'll have a look at the errors.

**Comment by drhelius** [comment]
This should fix PS3 and hopefully shouldn't break any other: https://github.com/drhelius/Gearboy/commit/44f6b10c5cd33dc82afe0590ab913351fafd983f

**Comment by drhelius** [comment]
This will help with iOS and improve Raspberry Pi too: https://github.com/drhelius/Gearboy/commit/6ef894a9036202bc81a1624428308dcf78a370b1

**Comment by fr500** [comment]
WiiU is working fine a user confirmed 👍

**Comment by drhelius** [comment]
Is there a place where I could take a look at the build outputs or are you building all those platforms on your pc?

**Comment by fr500** [comment]
build outputs as in logs?
http://buildbot.fiveforty.net/admin/buildbot/build/?name=gearboy

But you need login, we're always on discord and IRC, PM me for details

https://discord.gg/C4Huaca

**Comment by drhelius** [comment]
This should fix the new error in the PS3 build: https://github.com/drhelius/Gearboy/commit/0ec8fad8d1030d50699cd7b2beaa15bd609a7d73

**Comment by drhelius** [comment]
PS3 build fixed!
