### ISSUE TITLE
ppsspp requires files not listed as required by the .info

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-super#759]
This is the .info for ppsspp: https://github.com/libretro/libretro-super/blob/master/dist/info/ppsspp_libretro.info

PPSSPP requires quite a few files to operate, but currently only one file is listed as required firmware. That can cause confusion, such as in this thread: https://forums.libretro.com/t/trouble-getting-any-psp-title-to-run/14432

More information about the other files is listed in the docs: https://docs.libretro.com/library/ppsspp/

Is there any reason not to list every necessary PPSSPP file as required firmware in the .info?

**Comment by hizzlekizzle** [comment]
I guess it depends on how many it needs. If it's fewer than 10, it's probably a good idea to list them. If more, it might be best to just leave a note that describes what they need, e.g. "requires assets from PPSSPP standalone application" or whatever.

**Comment by markwkidd** [comment]
Closed by https://github.com/libretro/libretro-super/pull/765 hopefully that will be adequate. Thanks @Hedonium
