### ISSUE TITLE
[3DS] np2kai core missing since 1.7.1

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/libretro-super#797]
It was there in 1.7.0
Not in 1.7.1
Not in 1.7.2

anything we can do to the Travis CI to spot regressions like this?

**Comment by meepingsnesroms** [comment]
np2kai_libretro.3dsx is present in the 1.7.5 build
This should be closed.

**Comment by gingerbeardman** [comment]
This is missing again @meepingsnesroms shall I start a new issue?

1.7.5 = present
1.7.6 = present
1.7.7 = present
1.7.8 = missing
