### ISSUE TITLE
Gearboy rules is missing

### ISSUE THREAD

**Issue by Zarh** [libretro/libretro-super#812]
rules.d/cores-rules.sh

include_core_gearboy() {
	register_module core "gearboy"
}
libretro_gearboy_name="GearBOY"
libretro_gearboy_git_url="https://github.com/libretro/Gearboy.git"
libretro_gearboy_build_subdir="platforms/libretro"
libretro_gearboy_build_makefile="Makefile"

**Comment by Zarh** [comment]
same for mesen and gearsystem 

include_core_gearsystem() {
	register_module core "gearsystem"
}
libretro_gearsystem_name="Gearsystem"
libretro_gearsystem_git_url="https://github.com/drhelius/Gearsystem.git"
libretro_gearsystem_build_subdir="platforms/libretro"
libretro_gearsystem_build_makefile="Makefile"

include_core_mesen() {
	register_module core "mesen"
}
libretro_mesen_name="Mesen"
libretro_mesen_git_url="https://github.com/libretro/Mesen.git"
libretro_mesen_build_subdir="Libretro"
libretro_mesen_build_makefile="Makefile"

**Comment by drhelius** [comment]
Gearboy is already in, Gearsystem is waiting PR #1004
