### ISSUE TITLE
nSide Deprecated

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-super#824]
The author of nSide deprecated the project, and it looks like they also deleted their GitHub account:
https://github.com/hex-usr/nSide

We should either...
1. Remove the nside and higan-sfc-balanced references in libretro-super, or...
2. Find a backed up repository of it, and update the URLs

**Comment by bparker06** [comment]
I made a backup at https://github.com/libretro/nSide

**Comment by hizzlekizzle** [comment]
Is the deprecation 100% confirmed? I know there was a secondhand mention of it on byuu's forum, but I haven't heard anything directly from hex_usr. Switching to the backup repo is certainly prudent until the new repo is up either way.

**Comment by RobLoach** [comment]
I suppose he's moving it over to GitLab eventually:
https://board.byuu.org/viewtopic.php?f=4&t=2062

Think it'll eventually become a few small projects. Sounds great! :+1:

**Comment by RobLoach** [comment]
The PR is over at https://github.com/libretro/libretro-super/pull/825
