### ISSUE TITLE
[macOS] about box says 1.7.2 in 1.7.3

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/libretro-super#855]
![screen shot 2018-08-01 at 23 50 47](https://user-images.githubusercontent.com/49612/43553200-bee70292-95e5-11e8-8500-fe51d3f99633.png)

**Comment by hizzlekizzle** [comment]
Is this a nightly build or 1.7.3 stable? I ask because I just changed...something from 1.7.2 to 1.7.3 the other day, but it may need to be changed in other places, as well.

**Comment by gingerbeardman** [comment]
May 4th build

![screen shot 2018-08-02 at 20 35 25](https://user-images.githubusercontent.com/49612/43606567-a05a8318-9693-11e8-9425-38a289a40575.png)
