### ISSUE TITLE
Add Genode platform

### ISSUE THREAD

**Issue by ehmry** [libretro/libretro-super#913]
I maintain a [frontend](https://github.com/ehmry/genode-libretro/tree/master/src/app/retro_frontend) for the [Genode](genode.org) OS that I build cores for. Genode supports i686, x86_64, and ARM32 and runs on commodity hardware. It can act as userspace for several microkernels and has a hierarchical component-based structure. Libretro is nice for us because Libretro cores can usually be ported without modifications or maintenance. We also support SDL but Libretro is easier to map to our architecture.

I have a bunch of private patches for different core makefiles that I need to start publishing. I would like to add Genode support to `libretro-build.sh` and I would volunteer to make general improvements to the scripts and makefiles if it would make this easier.

Basically a Libretro core for Genode is a shared library that exports the Libretro symbols. For the sake of simplicity our frontend is linked to `libretro.lib.so` and when the frontend starts the dynamic loader must be configured to redirect this request to a concrete core library (this is normal for us).

To compile a Genode core, a copy of a Genode SDK must be present, and the SDK provides pkgconfig metadata for filling out the core build rules. For cores implemented in C the core would be linked to our libc library which behaves similar to FreeBSD. For C++ we link to our stdcxx library which provides all the `std::` stuff. Not necessary in the case of cores like Scummvm that only use bare C++, but not a problem if it is linked regardless. Normally I add a section like this to core makefiles:
```make
# Genode
else ifeq ($(platform), genode)
   TARGET  := $(TARGET_NAME)_libretro.lib.so
   PKG_CONFIG := genode-lib genode-stdcxx
   CXXFLAGS += -D__GENODE__
   CXXFLAGS += $(shell pkg-config --cflags $(PKG_CONFIG))

   LDFLAGS += -shared --version-script=link.T
   LDFLAGS += $(shell pkg-config --libs $(PKG_CONFIG))

   CC  = $(shell pkg-config genode-base --variable=cc)
   CXX = $(shell pkg-config genode-base --variable=cxx)
   LD  = $(shell pkg-config genode-base --variable=ld)
   AR  = $(shell pkg-config genode-base --variable=ar) -rcs
```

In this way both the compiler flags and cross-compiler are defined by pkgconfig, so this makefile would then be invoked by
`PKG_CONFIG_PATH="<SDK pkconfig dir>" make -f Makefile.libretro`.

The link step is complicated however, Genode cores cannot be built with `cc`, we explicitly need `ld`. An explicit libm library is passed during link through pkgconfig and `-lm` does not work because we disable linking any host libraries to the core.

What would be really nice would be to just define Genode like this in `libretro-config.sh` and make it work everywhere:
```shell
	genode-x86_64)
		DIST_DIR="genode-x86_64"
		FORMAT_EXT=lib.so
		FORMAT_COMPILER_TARGET=genode
		CC="$(pkg-config genode-base --variable=cc)"
		CXX="$(pkg-config genode-base --variable=cxx)"
		AR="$(pkg-config genode-base --variable=ar)"
		LD="$(pkg-config genode-base --variable=ld)"
		CFLAGS="$(pkg-config genode-libc --cflags)"
		CXXFLAGS="$(pkg-config genode-stdcxx --cflags)"
		LIBM=""
		;;
```

What can I do to make Genode support happen? I don't expect the buildbot to build for Genode because our frontend cannot download cores at runtime, but it would be nice for us to run a build script ourselves and then publish the results through our package manager.

**Comment by twinaphex** [comment]
Hi there, I'm completely fine and OK with supporting Genode upstream. Just send us the patches and the changes necessary and I'll happily merge. Every platform being added is a win in my book.

I'd even be fine with the buildbot building for Genode if that is desired, you would have to talk to one of the guys maintaining the buildbot though together with me so that we can discuss what needs to be installed on the buildbot server side to make that happen.

**Comment by ehmry** [comment]
I've given it thought and I've decided to split off into another "super" repo just for Genode - https://github.com/ehmry/genode-libretro. From there I will define my platform specific build recipes for each core using values provided by `Makefile.common` in each core repo. I will try to write up an article soon to explain how the build and deployment works.
